using System.Collections.Generic;
using Quests;

namespace Archipelago.TOEM;

public enum ApLocationId
{
    QuestPhotoOfNana = 1,
    QuestHiddenGift,
    QuestExperienceToem,
    CompCow,
    CompFlies,
    CompHomeBird,
    CompTato,
    ItemClogs,
    ItemAwardMask,
    TapePhotoOfHome,
    CheevoBeginning,
    CheevoHomeSweetHome,
    QuestSusForest,
    QuestMonsters,
    QuestSocks,
    QuestScouts,
    QuestHideAndSeek,
    QuestLogJam,
    QuestChallenge1,
    QuestChallenge2,
    QuestPaparazzi,
    QuestCaptureHotel,
    QuestHotelChef,
    QuestStallion,
    QuestGhostHelper,
    QuestCupChamp,
    QuestFlower,
    CompAnt,
    CompBeehive,
    CompButterfly,
    CompOskar,
    CompSero,
    CompForestBird,
    CompLadybug,
    CompTom,
    CompNestworm,
    CompPetRock,
    CompSnail,
    CompSquirrel,
    CompStagBeetle,
    CompTatoBug,
    CompTatoFly,
    ItemFinger,
    ItemTripod,
    ItemCowboyHat,
    ItemWetSocks,
    ItemFjallbjornHat,
    ItemGhostGlasses,
    ItemSoakedSock,
    ItemMonsterMask,
    TapeSquirrelPhoto,
    CheevoCalmForest,
    CheevoMajesticHotel,
    CheevoSlowAndSteady,
    CheevoNatureShowstopper,
    CheevoStrongAsAnOak,
    CheevoCalmedDown,
    CheevoJustASock,
    CheevoYouFoundUs,
    QuestKingFish,
    QuestGoodSpot,
    QuestSusHarbor,
    QuestPaperHats,
    QuestChallenge3,
    QuestChallenge4,
    QuestFramesFilters,
    QuestTakeABath,
    QuestLostDog,
    QuestPower,
    QuestChaos,
    QuestFlame,
    QuestSandwich,
    QuestGarbage,
    QuestWhistling,
    QuestMelody,
    CompBubbleFly,
    CompFia,
    CompFras,
    CompWillemijn,
    CompCrab,
    CompDragonfly,
    CompHappyCarp,
    CompJellyfish,
    CompKingFish,
    CompSeagull,
    CompSeahorse,
    CompSundaySwan,
    CompTatoScuba,
    CompTatoSwim,
    CompToad,
    ItemFramesFilters,
    ItemFishingHat,
    ItemHonkAttachment,
    ItemUmbrella,
    ItemOldKey,
    ItemHardHat,
    ItemDivingHelmet,
    ItemRubberBoots,
    ItemSandwich,
    ItemPirateHat,
    ItemPaperHat,
    ItemFlag,
    CheevoSetSail,
    CheevoVoyageUnderwater,
    CheevoEmployeeOfTheMonth,
    CheevoCalmAsSea,
    CheevoSeaworthy,
    CheevoFlightReady,
    CheevoSparklingJump,
    CheevoGoodBoy,
    QuestSusCity,
    QuestRatskullz,
    QuestPunkRocker,
    QuestChallenge5,
    QuestChallenge6,
    QuestNews,
    QuestSewer,
    QuestHotbean,
    QuestHangInThere,
    QuestScaryCity,
    QuestDate,
    QuestArt,
    QuestInfluencer,
    QuestFashion,
    QuestCleaning,
    QuestGranny,
    QuestMice,
    QuestCrow,
    CompBusinessPigeon,
    CompPortillo,
    CompMouse,
    CompPigeon,
    CompPunkParrot,
    CompTatoSkateboard,
    CompTatoTourist,
    CompTurtle,
    ItemHotbeanHat,
    ItemReporterHat,
    ItemSneakers,
    ItemCinnamonBun,
    ItemFrisbee,
    CheevoBigCity,
    CheevoClocktower,
    CheevoProfessional,
    CheevoBusiness,
    CheevoFollowers,
    CheevoNewJob,
    QuestYetiCute,
    QuestIceWizard,
    QuestMilitarySus,
    QuestAstronaut,
    QuestChallenge7,
    QuestChallenge8,
    QuestAsteroid,
    QuestGoatChoir,
    QuestSnowball,
    QuestBirthday,
    QuestPaintings,
    QuestBecomeYeti,
    QuestSnowman,
    CompMikee,
    CompNariko,
    CompCosmoDeer,
    CompTeddy,
    CompFluff,
    CompHedgehog,
    CompMeteopal,
    CompGoat,
    CompOwl,
    CompSnowBird,
    CompTatoAlien,
    CompTatoSki,
    ItemClimbingBoots,
    ItemPufferHat,
    ItemScarf,
    ItemSkiGoggles,
    ItemSpaceHelmet,
    CheevoSnowyPeaks,
    CheevoGearedUp,
    CheevoHurdle,
    CheevoFighter,
    CheevoYouth,
    CheevoStory,
    CheevoClose,
    CheevoToem,
    CheevoCuties,
    CheevoCollectEmAll,
    CheevoGoingLong,
    CheevoCosplayer,
    CheevoCompletionist,
    FirstBasto,
    QuestBalloons = FirstBasto,
    QuestArthur,
    QuestBadHairDay,
    QuestTakeANap,
    QuestSpookyStories,
    QuestPortraits,
    QuestCinema,
    QuestNightLights,
    QuestJetSki,
    QuestFruits,
    QuestBrainFreeze,
    QuestSweetTooth,
    QuestInYourFace,
    QuestBrokenDreams,
    QuestDrySeason,
    QuestMuscles,
    QuestSandCastle,
    QuestCarnival,
    QuestBats,
    QuestBitling,
    CompBat,
    CompSnake,
    CompBeakBird,
    CompBitlingFrog,
    CompBitlingMouse,
    CompBitlingSnail,
    CompBitlingTato,
    CompCocoCrab,
    CompDayLizard,
    CompDrillMole,
    CompEggert,
    CompFireFly,
    CompGlowWorm,
    CompItsyBitsy,
    CompMudFrog,
    CompNightLizard,
    CompSnoutBug,
    CompTatoCoco,
    CompTatoKing,
    CompWaterStrider,
    ItemWatergun,
    ItemSunHat,
    ItemMelonear,
    ItemBanakin,
    ItemOranganas,
    ItemBeanut,
    ItemPickaxe,
    ItemSunCap,
    ItemFlipFlops,
    ItemIceCream,
    ItemRoyalCape,
    ItemMinigameTicket,
    ItemLei,
    ItemVacationShirt,
    ItemRoyalCane,
    ItemEmptyBottle,
    ItemVikingHelmet,
    ItemFootCast,
    ItemBeret,
    ItemRoyalCrown,
}

public enum ApItemId
{
    StampHomelanda = 1,
    StampOaklaville,
    StampStanhamn,
    StampLogcity,
    StampKiiruberg,
    StampBasto,
    LastStamp = StampBasto,
    PhotoCow,
    PhotoFlies,
    PhotoHomeBird,
    PhotoTato,
    PhotoAnt,
    PhotoBeehive,
    PhotoButterfly,
    PhotoOskar,
    PhotoSero,
    PhotoForestBird,
    PhotoLadybug,
    PhotoTom,
    PhotoNestworm,
    PhotoPetRock,
    PhotoSnail,
    PhotoSquirrel,
    PhotoStagBeetle,
    PhotoTatoBug,
    PhotoTatoFly,
    PhotoBubbleFly,
    PhotoFia,
    PhotoFras,
    PhotoWillemijn,
    PhotoCrab,
    PhotoDragonfly,
    PhotoHappyCarp,
    PhotoJellyfish,
    PhotoKingFish,
    PhotoSeagull,
    PhotoSeahorse,
    PhotoSundaySwan,
    PhotoTatoScuba,
    PhotoTatoSwim,
    PhotoToad,
    PhotoBusinessPigeon,
    PhotoPortillo,
    PhotoMouse,
    PhotoPigeon,
    PhotoPunkParrot,
    PhotoTatoSkateboard,
    PhotoTatoTourist,
    PhotoTurtle,
    PhotoMikee,
    PhotoNariko,
    PhotoCosmoDeer,
    PhotoTeddy,
    PhotoFluff,
    PhotoHedgehog,
    PhotoMeteopal,
    PhotoGoat,
    PhotoOwl,
    PhotoSnowBird,
    PhotoTatoAlien,
    PhotoTatoSki,
    PhotoBat,
    PhotoSnake,
    PhotoBeakBird,
    PhotoBitlingFrog,
    PhotoBitlingMouse,
    PhotoBitlingSnail,
    PhotoBitlingTato,
    PhotoCocoCrab,
    PhotoDayLizard,
    PhotoDrillMole,
    PhotoEggert,
    PhotoFireFly,
    PhotoGlowWorm,
    PhotoItsyBitsy,
    PhotoMudFrog,
    PhotoNightLizard,
    PhotoSnoutBug,
    PhotoTatoCoco,
    PhotoTatoKing,
    PhotoWaterStrider,
    LastPhoto = PhotoWaterStrider,
    Clogs,
    AwardMask,
    Finger,
    Tripod,
    CowboyHat,
    WetSocks,
    FjallbjornHat,
    GhostGlasses,
    SoakedSock,
    MonsterMask,
    FramesFilters,
    FishingHat,
    HonkAttachment,
    Umbrella,
    OldKey,
    HardHat,
    DivingHelmet,
    RubberBoots,
    Sandwich,
    PirateHat,
    PaperHat,
    Flag,
    HotbeanHat,
    ReporterHat,
    Sneakers,
    CinnamonBun,
    Frisbee,
    ClimbingBoots,
    PufferHat,
    Scarf,
    SkiGoggles,
    SpaceHelmet,
    Watergun,
    SunHat,
    Melonear,
    Banakin,
    Oranganas,
    Beanut,
    Pickaxe,
    SunCap,
    FlipFlops,
    IceCream,
    RoyalCape,
    MinigameTicket,
    Lei,
    VacationShirt,
    RoyalCane,
    EmptyBottle,
    VikingHelmet,
    FootCast,
    Beret,
    RoyalCrown,
    LastItem = RoyalCrown,
}

public static class Data
{
    public static readonly Dictionary<string, ApLocationId> QuestToApLocationId = new() {
        {"Photo of Nana", ApLocationId.QuestPhotoOfNana},
        {"A Hidden Gift", ApLocationId.QuestHiddenGift},
        {"Experience TOEM", ApLocationId.QuestExperienceToem},
        {"Submarine - Forest", ApLocationId.QuestSusForest},
        {"Monster Collector", ApLocationId.QuestMonsters},
        {"Sockman", ApLocationId.QuestSocks},
        {"Become a scout - Scout Leader", ApLocationId.QuestScouts},
        {"Scout Hide And Seek", ApLocationId.QuestHideAndSeek},
        {"Pine Critters", ApLocationId.QuestLogJam},
        {"Photo Challenger Boy Forest", ApLocationId.QuestChallenge1},
        {"Photo Challenger Forest Girl", ApLocationId.QuestChallenge2},
        {"Paparazzi", ApLocationId.QuestPaparazzi},
        {"Hotel Owner - Capture Hotel's Beauty", ApLocationId.QuestCaptureHotel},
        {"Hotel Chef", ApLocationId.QuestHotelChef},
        {"Ghost Horse Stallion", ApLocationId.QuestStallion},
        {"Ghost Helper", ApLocationId.QuestGhostHelper},
        {"Ghost Cup", ApLocationId.QuestCupChamp},
        {"Become a Flower", ApLocationId.QuestFlower},
        {"The king of fishes", ApLocationId.QuestKingFish},
        {"Sunbather", ApLocationId.QuestGoodSpot},
        {"Submarine - Harbor", ApLocationId.QuestSusHarbor},
        {"Pirate Queen", ApLocationId.QuestPaperHats},
        {"Photo Challenger Boy Harbor", ApLocationId.QuestChallenge3},
        {"Photo Challenger Girl Harbor", ApLocationId.QuestChallenge4},
        {"Photo Challenger Frame", ApLocationId.QuestFramesFilters},
        {"Make someone take a bath", ApLocationId.QuestTakeABath},
        {"Lost Dog", ApLocationId.QuestLostDog},
        {"Hydroplant - Power shortage!", ApLocationId.QuestPower},
        {"Honk Master", ApLocationId.QuestChaos},
        {"Ghost Splat", ApLocationId.QuestFlame},
        {"Ghost Grumpy", ApLocationId.QuestSandwich},
        {"Fishing Tower", ApLocationId.QuestGarbage},
        {"Barry Whistle", ApLocationId.QuestWhistling},
        {"A layered melody", ApLocationId.QuestMelody},
        {"Submarine - City", ApLocationId.QuestSusCity},
        {"Ratskullz", ApLocationId.QuestRatskullz},
        {"Punk Rocker", ApLocationId.QuestPunkRocker},
        {"Photo Challenger Boy City", ApLocationId.QuestChallenge5},
        {"Photo Challenger Girl City", ApLocationId.QuestChallenge6},
        {"Office Director - Press-ing News", ApLocationId.QuestNews},
        {"Manhole", ApLocationId.QuestSewer},
        {"Hotbean Cart", ApLocationId.QuestHotbean},
        {"Hang in there buddy", ApLocationId.QuestHangInThere},
        {"Ghost Nature", ApLocationId.QuestScaryCity},
        {"Ghost Date", ApLocationId.QuestDate},
        {"Gallery Owner - Art Exhibition", ApLocationId.QuestArt},
        {"Food Influencer", ApLocationId.QuestInfluencer},
        {"Fashion Show - Design Problem", ApLocationId.QuestFashion},
        {"Cleaning away the stress", ApLocationId.QuestCleaning},
        {"Always Tumbled Granny", ApLocationId.QuestGranny},
        {"A Mouse Bakery", ApLocationId.QuestMice},
        {"A Thieving Crow", ApLocationId.QuestCrow},
        {"Yeti Cuteness", ApLocationId.QuestYetiCute},
        {"Wizard Inventor", ApLocationId.QuestIceWizard},
        {"Suspicious Activity - Military Base", ApLocationId.QuestMilitarySus},
        {"Play astronaut", ApLocationId.QuestAstronaut},
        {"Photo Challenger Boy Mountain", ApLocationId.QuestChallenge7},
        {"Photo Challenger Girl Mountain", ApLocationId.QuestChallenge8},
        {"Observatory Scientist", ApLocationId.QuestAsteroid},
        {"Goat Choir", ApLocationId.QuestGoatChoir},
        {"Snowball Memories", ApLocationId.QuestSnowball},
        {"Birthday Balloon In Distress", ApLocationId.QuestBirthday},
        {"Mountain Explorer", ApLocationId.QuestPaintings},
        {"Become a Yeti", ApLocationId.QuestBecomeYeti},
        {"Assemble a Snowman", ApLocationId.QuestSnowman},
        {"Bastu Balloons", ApLocationId.QuestBalloons},
        {"Treasure Hunter", ApLocationId.QuestArthur},
        {"Tangled Hair", ApLocationId.QuestBadHairDay},
        {"Take a nap", ApLocationId.QuestTakeANap},
        {"Spooky Story", ApLocationId.QuestSpookyStories},
        {"Painter - Closeup", ApLocationId.QuestPortraits},
        {"Nighttime Cinema", ApLocationId.QuestCinema},
        {"Night Lights", ApLocationId.QuestNightLights},
        {"Jetski Tricks", ApLocationId.QuestJetSki},
        {"Ice Cream Vendor", ApLocationId.QuestFruits},
        {"Ice Cream - Zombert", ApLocationId.QuestBrainFreeze},
        {"Ice Cream - Vampire", ApLocationId.QuestSweetTooth},
        {"Ice Cream - Prince", ApLocationId.QuestInYourFace},
        {"Ice Cream - Monkey", ApLocationId.QuestBrokenDreams},
        {"Dry Season", ApLocationId.QuestDrySeason},
        {"Dehydrated Muscles", ApLocationId.QuestMuscles},
        {"Castle Competition", ApLocationId.QuestSandCastle},
        {"Carnival Game", ApLocationId.QuestCarnival},
        {"Book of Bats", ApLocationId.QuestBats},
        {"Bitling Collector", ApLocationId.QuestBitling},
    };

    public static readonly Dictionary<string, ApLocationId> CreatureToApLocationId = new() {
        {"Cow", ApLocationId.CompCow},
        {"Flies", ApLocationId.CompFlies},
        {"Home Bird", ApLocationId.CompHomeBird},
        {"Tato", ApLocationId.CompTato},
        {"Ant", ApLocationId.CompAnt},
        {"Beehive", ApLocationId.CompBeehive},
        {"Butterfly", ApLocationId.CompButterfly},
        {"Oskar", ApLocationId.CompOskar},
        {"Sero", ApLocationId.CompSero},
        {"Forest Bird", ApLocationId.CompForestBird},
        {"Ladybug", ApLocationId.CompLadybug},
        {"Tom", ApLocationId.CompTom},
        {"Nestworm", ApLocationId.CompNestworm},
        {"Pet Rock", ApLocationId.CompPetRock},
        {"Snail", ApLocationId.CompSnail},
        {"Squirrel", ApLocationId.CompSquirrel},
        {"Stag Beetle", ApLocationId.CompStagBeetle},
        {"Tato Bug", ApLocationId.CompTatoBug},
        {"Tato Fly", ApLocationId.CompTatoFly},
        {"Bubble Fly", ApLocationId.CompBubbleFly},
        {"Fia", ApLocationId.CompFia},
        {"Fräs", ApLocationId.CompFras},
        {"Willemijn", ApLocationId.CompWillemijn},
        {"Crab", ApLocationId.CompCrab},
        {"Dragonfly", ApLocationId.CompDragonfly},
        {"Happy Carp", ApLocationId.CompHappyCarp},
        {"Jellyfish", ApLocationId.CompJellyfish},
        {"King Fish", ApLocationId.CompKingFish},
        {"Seagull", ApLocationId.CompSeagull},
        {"Seahorse", ApLocationId.CompSeahorse},
        {"Sunday Swan", ApLocationId.CompSundaySwan},
        {"Tato Scuba", ApLocationId.CompTatoScuba},
        {"Tato Swim", ApLocationId.CompTatoSwim},
        {"Toad", ApLocationId.CompToad},
        {"Business Pigeon", ApLocationId.CompBusinessPigeon},
        {"Portillo", ApLocationId.CompPortillo},
        {"Mouse", ApLocationId.CompMouse},
        {"Pigeon", ApLocationId.CompPigeon},
        {"Punk Parrot", ApLocationId.CompPunkParrot},
        {"Tato Skateboard", ApLocationId.CompTatoSkateboard},
        {"Tato Tourist", ApLocationId.CompTatoTourist},
        {"Turtle", ApLocationId.CompTurtle},
        {"Mikée", ApLocationId.CompMikee},
        {"Nariko", ApLocationId.CompNariko},
        {"Cosmo Deer", ApLocationId.CompCosmoDeer},
        {"Teddy", ApLocationId.CompTeddy},
        {"Fluff Ball", ApLocationId.CompFluff},
        {"Hedgehog", ApLocationId.CompHedgehog},
        {"Meteopal", ApLocationId.CompMeteopal},
        {"Mountain Goat", ApLocationId.CompGoat},
        {"Owl", ApLocationId.CompOwl},
        {"Snow Bird", ApLocationId.CompSnowBird},
        {"Tato Alien", ApLocationId.CompTatoAlien},
        {"Tato Ski", ApLocationId.CompTatoSki},
        {"Bat", ApLocationId.CompBat},
        {"Beach Snake", ApLocationId.CompSnake},
        {"Beak Bird", ApLocationId.CompBeakBird},
        {"Bitling Frog", ApLocationId.CompBitlingFrog},
        {"Bitling Mouse", ApLocationId.CompBitlingMouse},
        {"Bitling Snail", ApLocationId.CompBitlingSnail},
        {"Bitling Tato", ApLocationId.CompBitlingTato},
        {"Coco Crab", ApLocationId.CompCocoCrab},
        {"Day Lizard", ApLocationId.CompDayLizard},
        {"Drill Mole", ApLocationId.CompDrillMole},
        {"Eggert", ApLocationId.CompEggert},
        {"Fire Fly", ApLocationId.CompFireFly},
        {"Glow Worm", ApLocationId.CompGlowWorm},
        {"Itsy Bitsy", ApLocationId.CompItsyBitsy},
        {"Mud Frog", ApLocationId.CompMudFrog},
        {"Night Lizard", ApLocationId.CompNightLizard},
        {"Snout Bug", ApLocationId.CompSnoutBug},
        {"Tato Coco", ApLocationId.CompTatoCoco},
        {"Tato King", ApLocationId.CompTatoKing},
        {"Water Strider", ApLocationId.CompWaterStrider},
    };

    public static readonly Dictionary<string, ApLocationId> ItemToApLocationId = new() {
        {"Clogs", ApLocationId.ItemClogs},
        {"AwardMask", ApLocationId.ItemAwardMask},
        {"FoamFinger", ApLocationId.ItemFinger},
        {"Tripod", ApLocationId.ItemTripod},
        {"CowboyHat", ApLocationId.ItemCowboyHat},
        {"Pair of Socks", ApLocationId.ItemWetSocks},
        {"ScoutHat", ApLocationId.ItemFjallbjornHat},
        {"Sunglasses", ApLocationId.ItemGhostGlasses},
        {"Soaked Sock", ApLocationId.ItemSoakedSock},
        {"MonsterMask", ApLocationId.ItemMonsterMask},
        {"Camera Frames", ApLocationId.ItemFramesFilters},
        {"FishingHat", ApLocationId.ItemFishingHat},
        {"Honk", ApLocationId.ItemHonkAttachment},
        {"Umbrella", ApLocationId.ItemUmbrella},
        {"Pirate Key", ApLocationId.ItemOldKey},
        {"Hardhat", ApLocationId.ItemHardHat},
        {"DiverHelmet", ApLocationId.ItemDivingHelmet},
        {"Rubber Boots", ApLocationId.ItemRubberBoots},
        {"SupremeSandwich", ApLocationId.ItemSandwich},
        {"PirateHat", ApLocationId.ItemPirateHat},
        {"PaperHat", ApLocationId.ItemPaperHat},
        {"PhotoFlag", ApLocationId.ItemFlag},
        {"Hotbean Hat", ApLocationId.ItemHotbeanHat},
        {"ReporterHat", ApLocationId.ItemReporterHat},
        {"Sneakers", ApLocationId.ItemSneakers},
        {"Cinnamonbun", ApLocationId.ItemCinnamonBun},
        {"Frisbee", ApLocationId.ItemFrisbee},
        {"Snow Boots", ApLocationId.ItemClimbingBoots},
        {"Puff Hat", ApLocationId.ItemPufferHat},
        {"Scarf", ApLocationId.ItemScarf},
        {"SkiGoggles", ApLocationId.ItemSkiGoggles},
        {"SpaceHelmet", ApLocationId.ItemSpaceHelmet},
        {"Water Balloon", ApLocationId.ItemWatergun},
        {"Sunhat", ApLocationId.ItemSunHat},
        {"Fruit Pear", ApLocationId.ItemMelonear},
        {"Fruit Banana", ApLocationId.ItemBanakin},
        {"Fruit Orange", ApLocationId.ItemOranganas},
        {"Fruit Bean", ApLocationId.ItemBeanut},
        {"Pickaxe", ApLocationId.ItemPickaxe},
        {"Suncap", ApLocationId.ItemSunCap},
        {"Flipflops", ApLocationId.ItemFlipFlops},
        {"Ice Cream", ApLocationId.ItemIceCream},
        {"Royal Cape", ApLocationId.ItemRoyalCape},
        {"MiniGame Ticket", ApLocationId.ItemMinigameTicket},
        {"Lei", ApLocationId.ItemLei},
        {"Vacation Shirt", ApLocationId.ItemVacationShirt},
        {"Royal Cane", ApLocationId.ItemRoyalCane},
        {"Water Bottle Empty", ApLocationId.ItemEmptyBottle},
        {"Viking Helmet", ApLocationId.ItemVikingHelmet},
        {"Foot Cast", ApLocationId.ItemFootCast},
        {"Beret", ApLocationId.ItemBeret},
        {"Crown", ApLocationId.ItemRoyalCrown},
    };

    public static readonly Dictionary<ApLocationId, ApItemId> ApLocationIdToApItemId = new() {
        {ApLocationId.ItemClogs, ApItemId.Clogs},
        {ApLocationId.ItemAwardMask, ApItemId.AwardMask},
        {ApLocationId.ItemFinger, ApItemId.Finger},
        {ApLocationId.ItemTripod, ApItemId.Tripod},
        {ApLocationId.ItemCowboyHat, ApItemId.CowboyHat},
        {ApLocationId.ItemWetSocks, ApItemId.WetSocks},
        {ApLocationId.ItemFjallbjornHat, ApItemId.FjallbjornHat},
        {ApLocationId.ItemGhostGlasses, ApItemId.GhostGlasses},
        {ApLocationId.ItemSoakedSock, ApItemId.SoakedSock},
        {ApLocationId.ItemMonsterMask, ApItemId.MonsterMask},
        {ApLocationId.ItemFramesFilters, ApItemId.FramesFilters},
        {ApLocationId.ItemFishingHat, ApItemId.FishingHat},
        {ApLocationId.ItemHonkAttachment, ApItemId.HonkAttachment},
        {ApLocationId.ItemUmbrella, ApItemId.Umbrella},
        {ApLocationId.ItemOldKey, ApItemId.OldKey},
        {ApLocationId.ItemHardHat, ApItemId.HardHat},
        {ApLocationId.ItemDivingHelmet, ApItemId.DivingHelmet},
        {ApLocationId.ItemRubberBoots, ApItemId.RubberBoots},
        {ApLocationId.ItemSandwich, ApItemId.Sandwich},
        {ApLocationId.ItemPirateHat, ApItemId.PirateHat},
        {ApLocationId.ItemPaperHat, ApItemId.PaperHat},
        {ApLocationId.ItemFlag, ApItemId.Flag},
        {ApLocationId.ItemHotbeanHat, ApItemId.HotbeanHat},
        {ApLocationId.ItemReporterHat, ApItemId.ReporterHat},
        {ApLocationId.ItemSneakers, ApItemId.Sneakers},
        {ApLocationId.ItemCinnamonBun, ApItemId.CinnamonBun},
        {ApLocationId.ItemFrisbee, ApItemId.Frisbee},
        {ApLocationId.ItemClimbingBoots, ApItemId.ClimbingBoots},
        {ApLocationId.ItemPufferHat, ApItemId.PufferHat},
        {ApLocationId.ItemScarf, ApItemId.Scarf},
        {ApLocationId.ItemSkiGoggles, ApItemId.SkiGoggles},
        {ApLocationId.ItemSpaceHelmet, ApItemId.SpaceHelmet},
        {ApLocationId.ItemWatergun, ApItemId.Watergun},
        {ApLocationId.ItemSunHat, ApItemId.SunHat},
        {ApLocationId.ItemMelonear, ApItemId.Melonear},
        {ApLocationId.ItemBanakin, ApItemId.Banakin},
        {ApLocationId.ItemOranganas, ApItemId.Oranganas},
        {ApLocationId.ItemBeanut, ApItemId.Beanut},
        {ApLocationId.ItemPickaxe, ApItemId.Pickaxe},
        {ApLocationId.ItemSunCap, ApItemId.SunCap},
        {ApLocationId.ItemFlipFlops, ApItemId.FlipFlops},
        {ApLocationId.ItemIceCream, ApItemId.IceCream},
        {ApLocationId.ItemRoyalCape, ApItemId.RoyalCape},
        {ApLocationId.ItemMinigameTicket, ApItemId.MinigameTicket},
        {ApLocationId.ItemLei, ApItemId.Lei},
        {ApLocationId.ItemVacationShirt, ApItemId.VacationShirt},
        {ApLocationId.ItemRoyalCane, ApItemId.RoyalCane},
        {ApLocationId.ItemEmptyBottle, ApItemId.EmptyBottle},
        {ApLocationId.ItemVikingHelmet, ApItemId.VikingHelmet},
        {ApLocationId.ItemFootCast, ApItemId.FootCast},
        {ApLocationId.ItemBeret, ApItemId.Beret},
        {ApLocationId.ItemRoyalCrown, ApItemId.RoyalCrown},
    };

    public static readonly Dictionary<ApItemId, Quest.QuestRegion> ApItemIdToQuestRegion = new() {
        {ApItemId.StampHomelanda, Quest.QuestRegion.Home},
        {ApItemId.StampOaklaville, Quest.QuestRegion.Forest},
        {ApItemId.StampStanhamn, Quest.QuestRegion.Harbor},
        {ApItemId.StampLogcity, Quest.QuestRegion.City},
        {ApItemId.StampKiiruberg, Quest.QuestRegion.Mountain},
        {ApItemId.StampBasto, Quest.QuestRegion.Resort},
    };
    
    public static readonly Dictionary<ApItemId, string> ApItemIdToItem = new() {
        {ApItemId.Clogs, "Clogs"},
        {ApItemId.AwardMask, "AwardMask"},
        {ApItemId.Finger, "FoamFinger"},
        {ApItemId.Tripod, "Tripod"},
        {ApItemId.CowboyHat, "CowboyHat"},
        {ApItemId.WetSocks, "Pair of Socks"},
        {ApItemId.FjallbjornHat, "ScoutHat"},
        {ApItemId.GhostGlasses, "Sunglasses"},
        {ApItemId.SoakedSock, "Soaked Sock"},
        {ApItemId.MonsterMask, "MonsterMask"},
        {ApItemId.FramesFilters, "Camera Frames"},
        {ApItemId.FishingHat, "FishingHat"},
        {ApItemId.HonkAttachment, "Honk"},
        {ApItemId.Umbrella, "Umbrella"},
        {ApItemId.OldKey, "Pirate Key"},
        {ApItemId.HardHat, "Hardhat"},
        {ApItemId.DivingHelmet, "DiverHelmet"},
        {ApItemId.RubberBoots, "Rubber Boots"},
        {ApItemId.Sandwich, "SupremeSandwich"},
        {ApItemId.PirateHat, "PirateHat"},
        {ApItemId.PaperHat, "PaperHat"},
        {ApItemId.Flag, "PhotoFlag"},
        {ApItemId.HotbeanHat, "Hotbean Hat"},
        {ApItemId.ReporterHat, "ReporterHat"},
        {ApItemId.Sneakers, "Sneakers"},
        {ApItemId.CinnamonBun, "Cinnamonbun"},
        {ApItemId.Frisbee, "Frisbee"},
        {ApItemId.ClimbingBoots, "Snow Boots"},
        {ApItemId.PufferHat, "Puff Hat"},
        {ApItemId.Scarf, "Scarf"},
        {ApItemId.SkiGoggles, "SkiGoggles"},
        {ApItemId.SpaceHelmet, "SpaceHelmet"},
        {ApItemId.Watergun, "Water Balloon Popper Attachment"},
        {ApItemId.SunHat, "Sunhat"},
        {ApItemId.Melonear, "Fruit Pear"},
        {ApItemId.Banakin, "Fruit Banana"},
        {ApItemId.Oranganas, "Fruit Orange"},
        {ApItemId.Beanut, "Fruit Bean"},
        {ApItemId.Pickaxe, "Pickaxe"},
        {ApItemId.SunCap, "Suncap"},
        {ApItemId.FlipFlops, "Flipflops"},
        {ApItemId.IceCream, "Ice Cream"},
        {ApItemId.RoyalCape, "Royal Cape"},
        {ApItemId.MinigameTicket, "MiniGame Ticket"},
        {ApItemId.Lei, "Lei"},
        {ApItemId.VacationShirt, "Vacation Shirt"},
        {ApItemId.RoyalCane, "Royal Cane"},
        {ApItemId.EmptyBottle, "Water Bottle Empty"},
        {ApItemId.VikingHelmet, "Viking Helmet"},
        {ApItemId.FootCast, "Foot Cast"},
        {ApItemId.Beret, "Beret"},
        {ApItemId.RoyalCrown, "Royal Crown"},
    };
}
