using System;
using System.Collections.Generic;
using Quests;

namespace Archipelago.TOEM;

public enum ApLocationId
{
    QuestPhotoOfNana = 1,
    QuestHiddenGift,
    QuestExperienceToem,
    CompCow,
    CompFlies,
    CompHomeBird,
    CompTato,
    ItemClogs,
    ItemAwardMask,
    TapePhotoOfHome,
    CheevoBeginning,
    CheevoHomeSweetHome,
    QuestSusForest,
    QuestMonsters,
    QuestSocks,
    QuestScouts,
    QuestHideAndSeek,
    QuestLogJam,
    QuestChallenge1,
    QuestChallenge2,
    QuestPaparazzi,
    QuestCaptureHotel,
    QuestHotelChef,
    QuestStallion,
    QuestGhostHelper,
    QuestCupChamp,
    QuestFlower,
    CompAnt,
    CompBeehive,
    CompButterfly,
    CompOskar,
    CompSero,
    CompForestBird,
    CompLadybug,
    CompTom,
    CompNestworm,
    CompPetRock,
    CompSnail,
    CompSquirrel,
    CompStagBeetle,
    CompTatoBug,
    CompTatoFly,
    ItemFinger,
    ItemTripod,
    ItemCowboyHat,
    ItemWetSocks,
    ItemFjallbjornHat,
    ItemGhostGlasses,
    ItemSoakedSock,
    ItemMonsterMask,
    TapeSummerBreeze,
    TapeSquirrelHotel,
    TapePineNeedles,
    TapeSquirrelPhoto,
    CheevoCalmForest,
    CheevoMajesticHotel,
    CheevoSlowAndSteady,
    CheevoNatureShowstopper,
    CheevoStrongAsAnOak,
    CheevoCalmedDown,
    CheevoJustASock,
    CheevoYouFoundUs,
    QuestKingFish,
    QuestGoodSpot,
    QuestSusHarbor,
    QuestPaperHats,
    QuestChallenge3,
    QuestChallenge4,
    QuestFramesFilters,
    QuestTakeABath,
    QuestLostDog,
    QuestPower,
    QuestChaos,
    QuestFlame,
    QuestSandwich,
    QuestGarbage,
    QuestWhistling,
    QuestMelody,
    CompBubbleFly,
    CompFia,
    CompFras,
    CompWillemijn,
    CompCrab,
    CompDragonfly,
    CompHappyCarp,
    CompJellyfish,
    CompKingFish,
    CompSeagull,
    CompSeahorse,
    CompSundaySwan,
    CompTatoScuba,
    CompTatoSwim,
    CompToad,
    ItemFramesFilters,
    ItemFishingHat,
    ItemHonkAttachment,
    ItemUmbrella,
    ItemOldKey,
    ItemHardHat,
    ItemDivingHelmet,
    ItemRubberBoots,
    ItemSandwich,
    ItemPirateHat,
    ItemPaperHat,
    ItemFlag,
    TapeFishermansWhistle,
    TapeSmilingHuntsman,
    TapeNaut,
    TapePlaceInSun,
    TapeFishermansTune,
    CheevoSetSail,
    CheevoVoyageUnderwater,
    CheevoEmployeeOfTheMonth,
    CheevoCalmAsSea,
    CheevoSeaworthy,
    CheevoFlightReady,
    CheevoSparklingJump,
    CheevoGoodBoy,
    QuestSusCity,
    QuestRatskullz,
    QuestPunkRocker,
    QuestChallenge5,
    QuestChallenge6,
    QuestNews,
    QuestSewer,
    QuestHotbean,
    QuestHangInThere,
    QuestScaryCity,
    QuestDate,
    QuestArt,
    QuestInfluencer,
    QuestFashion,
    QuestCleaning,
    QuestGranny,
    QuestMice,
    QuestCrow,
    CompBusinessPigeon,
    CompPortillo,
    CompMouse,
    CompPigeon,
    CompPunkParrot,
    CompTatoSkateboard,
    CompTatoTourist,
    CompTurtle,
    ItemHotbeanHat,
    ItemReporterHat,
    ItemSneakers,
    ItemCinnamonBun,
    ItemFrisbee,
    TapeRatskullzTheme,
    TapeBigCity,
    TapeHustleBustle,
    TapeHopSkipStep,
    TapeOnTheHour,
    CheevoBigCity,
    CheevoClocktower,
    CheevoProfessional,
    CheevoBusiness,
    CheevoFollowers,
    CheevoNewJob,
    QuestYetiCute,
    QuestIceWizard,
    QuestMilitarySus,
    QuestAstronaut,
    QuestChallenge7,
    QuestChallenge8,
    QuestAsteroid,
    QuestGoatChoir,
    QuestSnowball,
    QuestBirthday,
    QuestPaintings,
    QuestBecomeYeti,
    QuestSnowman,
    CompMikee,
    CompNariko,
    CompCosmoDeer,
    CompTeddy,
    CompFluff,
    CompHedgehog,
    CompMeteopal,
    CompGoat,
    CompOwl,
    CompSnowBird,
    CompTatoAlien,
    CompTatoSki,
    ItemClimbingBoots,
    ItemPufferHat,
    ItemScarf,
    ItemSkiGoggles,
    ItemSpaceHelmet,
    TapeLifeThroughLens,
    TapePettingDeer,
    TapeStoriesOfSnow,
    TapeTallShy,
    CheevoSnowyPeaks,
    CheevoGearedUp,
    CheevoHurdle,
    CheevoFighter,
    CheevoYouth,
    CheevoStory,
    CheevoClose,
    CheevoToem,
    CheevoCuties,
    CheevoCollectEmAll,
    CheevoGoingLong,
    CheevoCosplayer,
    CheevoCompletionist,
    FirstBasto,
    QuestBalloons = FirstBasto,
    QuestArthur,
    QuestBadHairDay,
    QuestTakeANap,
    QuestSpookyStories,
    QuestPortraits,
    QuestCinema,
    QuestNightLights,
    QuestJetSki,
    QuestFruits,
    QuestBrainFreeze,
    QuestSweetTooth,
    QuestInYourFace,
    QuestBrokenDreams,
    QuestDrySeason,
    QuestMuscles,
    QuestSandCastle,
    QuestCarnival,
    QuestBats,
    QuestBitling,
    CompBat,
    CompSnake,
    CompBeakBird,
    CompBitlingFrog,
    CompBitlingMouse,
    CompBitlingSnail,
    CompBitlingTato,
    CompCocoCrab,
    CompDayLizard,
    CompDrillMole,
    CompEggert,
    CompFireFly,
    CompGlowWorm,
    CompItsyBitsy,
    CompMudFrog,
    CompNightLizard,
    CompSnoutBug,
    CompTatoCoco,
    CompTatoKing,
    CompWaterStrider,
    ItemBastoTicket,
    ItemWatergun,
    ItemSunHat,
    ItemMelonear,
    ItemBanakin,
    ItemOranganas,
    ItemBeanut,
    ItemPickaxe,
    ItemSunCap,
    ItemFlipFlops,
    ItemIceCreamBanakin,
    ItemIceCreamMelonear,
    ItemIceCreamBeanut,
    ItemIceCreamOranganas,
    ItemRoyalCape,
    ItemMinigameTicket,
    ItemLei,
    ItemVacationShirt,
    ItemRoyalCane,
    ItemEmptyBottle,
    ItemVikingHelmet,
    ItemFootCast,
    ItemBeret,
    ItemRoyalCrown,
    TapeNightJam,
    TapeWarmDaysNight,
    TapeOneByOne,
    TapeHammockDays,
    TapeSailorsTune,
    TapeSongOfTheSea,
    CheevoTropicalParadise,
    CheevoMaximumVacation,
    CheevoKingsShirt,
    CheevoMoonlitBeauty,
    CheevoSelfPortrait,
    CheevoWazzuuppp,
    CheevoProGamer,
    CheevoSplishSplash,
    CheevoRoyalCastle,
    CheevoSomeMore,
    CheevoVikingsHoliday,
}

public enum ApItemId
{
    StampHomelanda = 1,
    StampOaklaville,
    StampStanhamn,
    StampLogcity,
    StampKiiruberg,
    StampBasto,
    ProgressiveStamp,
    LastStamp = ProgressiveStamp,
    PhotoCow,
    PhotoFlies,
    PhotoHomeBird,
    PhotoTato,
    PhotoAnt,
    PhotoBeehive,
    PhotoButterfly,
    PhotoOskar,
    PhotoSero,
    PhotoForestBird,
    PhotoLadybug,
    PhotoTom,
    PhotoNestworm,
    PhotoPetRock,
    PhotoSnail,
    PhotoSquirrel,
    PhotoStagBeetle,
    PhotoTatoBug,
    PhotoTatoFly,
    PhotoBubbleFly,
    PhotoFia,
    PhotoFras,
    PhotoWillemijn,
    PhotoCrab,
    PhotoDragonfly,
    PhotoHappyCarp,
    PhotoJellyfish,
    PhotoKingFish,
    PhotoSeagull,
    PhotoSeahorse,
    PhotoSundaySwan,
    PhotoTatoScuba,
    PhotoTatoSwim,
    PhotoToad,
    PhotoBusinessPigeon,
    PhotoPortillo,
    PhotoMouse,
    PhotoPigeon,
    PhotoPunkParrot,
    PhotoTatoSkateboard,
    PhotoTatoTourist,
    PhotoTurtle,
    PhotoMikee,
    PhotoNariko,
    PhotoCosmoDeer,
    PhotoTeddy,
    PhotoFluff,
    PhotoHedgehog,
    PhotoMeteopal,
    PhotoGoat,
    PhotoOwl,
    PhotoSnowBird,
    PhotoTatoAlien,
    PhotoTatoSki,
    PhotoBat,
    PhotoSnake,
    PhotoBeakBird,
    PhotoBitlingFrog,
    PhotoBitlingMouse,
    PhotoBitlingSnail,
    PhotoBitlingTato,
    PhotoCocoCrab,
    PhotoDayLizard,
    PhotoDrillMole,
    PhotoEggert,
    PhotoFireFly,
    PhotoGlowWorm,
    PhotoItsyBitsy,
    PhotoMudFrog,
    PhotoNightLizard,
    PhotoSnoutBug,
    PhotoTatoCoco,
    PhotoTatoKing,
    PhotoWaterStrider,
    LastPhoto = PhotoWaterStrider,
    Clogs,
    AwardMask,
    Finger,
    Tripod,
    CowboyHat,
    WetSocks,
    FjallbjornHat,
    GhostGlasses,
    SoakedSock,
    MonsterMask,
    FramesFilters,
    FishingHat,
    HonkAttachment,
    Umbrella,
    OldKey,
    HardHat,
    DivingHelmet,
    RubberBoots,
    Sandwich,
    PirateHat,
    PaperHat,
    Flag,
    HotbeanHat,
    ReporterHat,
    Sneakers,
    CinnamonBun,
    Frisbee,
    ClimbingBoots,
    PufferHat,
    Scarf,
    SkiGoggles,
    SpaceHelmet,
    BastoTicket,
    Watergun,
    SunHat,
    Melonear,
    Banakin,
    Oranganas,
    Beanut,
    Pickaxe,
    SunCap,
    FlipFlops,
    IceCream,
    RoyalCape,
    MinigameTicket,
    Lei,
    VacationShirt,
    RoyalCane,
    EmptyBottle,
    VikingHelmet,
    FootCast,
    Beret,
    RoyalCrown,
    LastItem = RoyalCrown,
    PhotoOfHomeTape,
    SummerBreezeTape,
    SquirrelHotelTape,
    PineNeedlesTape,
    SquirrelPhotoTape,
    FishermansWhistleTape,
    SmilingHuntsmanTape,
    NautTape,
    PlaceInSunTape,
    FishermansTuneTape,
    RatskullzThemeTape,
    BigCityTape,
    HustleBustleTape,
    HopSkipStepTape,
    OnTheHourTape,
    LifeThroughLensTape,
    PettingDeerTape,
    StoriesOfSnowTape,
    TallShyTape,
    NightJamTape,
    WarmDaysNightTape,
    OneByOneTape,
    HammockDaysTape,
    SailorsTuneTape,
    SongOfTheSeaTape,
    LastCassette = SongOfTheSeaTape,
}

public enum ApConnectionId
{
    // Menu
    StartGame = 1,
    HomelandaBusStop,
    OaklavilleBusStop,
    StanhamnBusStop,
    LogcityBusStop,
    KiirubergBusStop,
    MountainTopBusStop,
    // Homelanda
    PlayerRoomExit,
    PlayerRoomEntrance,
    HomelandaHouseExit,
    HomelandaHouseEntrance,
    HomelandaBusPickup,
    // Oaklaville
    OaklavilleBusPickup,
    OaklavilleBusStopExit,
    OutsideHotelDown,
    OutsideHotelLeft,
    OutsideHotelRight,
    HotelEntrance,
    HotelExit,
    HotelElevatorEntrance,
    HotelElevatorExit,
    GhostCupGameRight,
    MushroomHouseEntrance,
    GhostCupGameLeft,
    MushroomHouseExit,
    HideAndSeekRight,
    HideAndSeekLeft,
    GraveyardRight,
    SkeletonHouseEntrance,
    SkeletonHouseExit,
    SkeletonHouseBalconyExit,
    SkeletonHouseBalconyEntrance,
    ScoutCampLeft,
    ScoutCampUp,
    ScoutCampRight,
    OaklavilleTrailLogFromTop,
    OaklavilleTrailUp,
    OaklavilleTrailLogFromBottom,
    OaklavilleTrailDown,
    LookoutExit,
    PlaygroundLeft,
    PlaygroundRight,
    RaveBouncerFromTop,
    RaveEntrance,
    RaveBouncerFromBottom,
    OutsideRaveLeft,
    RaveExit,
    // Stanhamn
    StanhamnBusPickup,
    PhotoGuildHutEntrance,
    StanhamnBusStopLeft,
    StanhamnBusStopRight,
    RaftUp,
    PhotoGuildHutExit,
    PirateDrawbridgeRight,
    PirateDrawbridgeLeft,
    HippoBeachRight,
    HippoBeachManhole,
    HippoBeachLeft,
    UnderwaterExit,
    OutsideLighthouseRight,
    OutsideLighthouseUp,
    LighthouseEntrance,
    LighthouseExit,
    LighthouseRoofEntrance,
    LighthouseRoofExit,
    KingFishBeachExit,
    DocksLeftExit,
    VikingExpressStamhamnStop,
    DocksDrawbridgeFromLeft,
    DocksRightExit,
    DocksDrawbridgeFromRight,
    FishingTowerLeft,
    FishingTowerUp,
    GhostDrawbridgeLeft,
    GhostDrawbridgeFromTop,
    GhostDrawbridgeDown,
    GhostDrawbridgeFromBottom,
    RaftDown,
    HydroplantEntrance,
    OutsideHydroplantRight,
    HydroplantExit,
    // Logcity
    LogcityBusPickup,
    EscalatorUp,
    LogcityBusStopEntrance,
    ClockTowerLeft,
    ClockTowerUp,
    ClockTowerRight,
    CrossWalkRight,
    CrossWalkUp,
    OverpassDown,
    NewsHouseEntrance,
    OverpassUp,
    OverpassRight,
    NewsHouseExit,
    SkateParkDown,
    SkateParkRight,
    SkateParkTaxi,
    RatskullzAlleyExit,
    FashionShowEntrance,
    OutsideFashionShowDown,
    OutsideFashionShowLeft,
    OutsideFashionShowRight,
    FashionShowSecurityFromTop,
    FashionShowBackstageEntrance,
    FashionShowSecurityFromBottom,
    FashionShowExit,
    FashionShowBackstageExit,
    CafeEntrance,
    OutsideCafeLeft,
    OutsideCafeUp,
    OutsideCafeTaxi,
    CafeExit,
    GalleryEntrance,
    OutsideGalleryShowDown,
    OutsideGalleryShowLeft,
    GalleryExit,
    // Kiiruberg
    KiirubergBusPickup,
    KiirubergBusStopUp,
    BirthdayPartyRopeFromBottom,
    BalloonHouseEntrance,
    BirthdayPartyDown,
    BirthdayPartyLeft,
    BirthdayPartyRight,
    BirthdayPartyRopeFromTop,
    BirthdayPartyUp,
    BalloonHouseExit,
    OldMansHouseEntrance,
    FrozenPondRight,
    OldMansHouseExit,
    SnowmanSquareRopeFromBottom,
    MilitaryBaseEntrance,
    MecksHouseEntrance,
    SnowmanSquareDown,
    SnowmanSquareRopeFromTop,
    SnowmanSquareLeft,
    SnowmanSquareUp,
    MilitaryBaseExit,
    MecksHouseExit,
    WizardTowerEntrance,
    OutsideWizardTowerRight,
    WizardPortalEntrance,
    WizardTowerExit,
    WizardPortalExit,
    CliffsDown,
    CliffsBottomRopeFromBottom,
    CliffsRight,
    CliffsBottomRopeFromMiddle,
    CliffsTopRopeFromMiddle,
    CliffsUp,
    CliffsTopRopeFromTop,
    BlizzardBridgeLeft,
    BlizzardBridgeRopeFromLowerLeft,
    BlizzardBridgeBreakIceFromBottom,
    ManCaveEntrance,
    BlizzardBridgeRopeFromUpperLeft,
    BlizzardBridgeBreakIceFromTop,
    BlizzardBridgeRopeFromLowerRight,
    BlizzardBridgeRopeFromUpperRight,
    BlizzardBridgeRight,
    ManCaveExit,
    BlizzardMonsterExit,
    ObservatoryEntrance,
    OutsideObservatoryRopeFromTop,
    OutsideObservatoryRopeFromBottom,
    OutsideObservatoryDown,
    OutsideObservatoryRight,
    ObservatoryExit,
    SkiLodgeEntrance,
    SkiLiftBaseLeft,
    SkiLiftUp,
    SkiLodgeExit,
    SkiMountainTopLeft,
    SkiLiftDown,
    // Mountain top
    MountainTopBusPickup,
    MountainTopBusStopClimb,
    ToemDescend,
    // Basto
    BastoHarborGateFromTop,
    BastoHarborUp,
    BastoHarborGateFromBottom,
    VikingExpressBastoStop,
    LilyPadPondDown,
    LilyPadPondLeft,
    LilyPadPondNightBridgeFromLeft,
    LilyPadPondRight,
    LilyPadPondUp,
    LilyPadPondNightBridgeFromRight,
    TentEntrance,
    CampsiteRight,
    TentExit,
    CastleEntrance,
    GymHouseEntrance,
    OutsideCastleDown,
    OutsideCastleLeft,
    CastleExit,
    GymHouseExit,
    BonfireLowerRight,
    BonfireUpperRight,
    BonfireDayBridgeFromTop,
    CarnivalEntrance,
    BonfireDayBridgeFromBottom,
    CarnivalExit,
    GhostHangoutCaveEntrance,
    GhostHangoutLeft,
    SecretCaveRoomEntrance,
    GhostHangoutCaveExit,
    JungleCaveExit,
    SecretCaveRoomExit,
    JungleCaveEntrance,
    JungleLeft,
}

public static class Data
{
    public static readonly Dictionary<string, ApLocationId> QuestToApLocationId = new() {
        {"Photo of Nana", ApLocationId.QuestPhotoOfNana},
        {"A Hidden Gift", ApLocationId.QuestHiddenGift},
        {"Experience TOEM", ApLocationId.QuestExperienceToem},
        {"Submarine - Forest", ApLocationId.QuestSusForest},
        {"Monster Collector", ApLocationId.QuestMonsters},
        {"Sockman", ApLocationId.QuestSocks},
        {"Become a scout - Scout Leader", ApLocationId.QuestScouts},
        {"Scout Hide And Seek", ApLocationId.QuestHideAndSeek},
        {"Pine Critters", ApLocationId.QuestLogJam},
        {"Photo Challenger Boy Forest", ApLocationId.QuestChallenge1},
        {"Photo Challenger Forest Girl", ApLocationId.QuestChallenge2},
        {"Paparazzi", ApLocationId.QuestPaparazzi},
        {"Hotel Owner - Capture Hotel's Beauty", ApLocationId.QuestCaptureHotel},
        {"Hotel Chef", ApLocationId.QuestHotelChef},
        {"Ghost Horse Stallion", ApLocationId.QuestStallion},
        {"Ghost Helper", ApLocationId.QuestGhostHelper},
        {"Ghost Cup", ApLocationId.QuestCupChamp},
        {"Become a Flower", ApLocationId.QuestFlower},
        {"The king of fishes", ApLocationId.QuestKingFish},
        {"Sunbather", ApLocationId.QuestGoodSpot},
        {"Submarine - Harbor", ApLocationId.QuestSusHarbor},
        {"Pirate Queen", ApLocationId.QuestPaperHats},
        {"Photo Challenger Boy Harbor", ApLocationId.QuestChallenge3},
        {"Photo Challenger Girl Harbor", ApLocationId.QuestChallenge4},
        {"Photo Challenger Frame", ApLocationId.QuestFramesFilters},
        {"Make someone take a bath", ApLocationId.QuestTakeABath},
        {"Lost Dog", ApLocationId.QuestLostDog},
        {"Hydroplant - Power shortage!", ApLocationId.QuestPower},
        {"Honk Master", ApLocationId.QuestChaos},
        {"Ghost Splat", ApLocationId.QuestFlame},
        {"Ghost Grumpy", ApLocationId.QuestSandwich},
        {"Fishing Tower", ApLocationId.QuestGarbage},
        {"Barry Whistle", ApLocationId.QuestWhistling},
        {"A layered melody", ApLocationId.QuestMelody},
        {"Submarine - City", ApLocationId.QuestSusCity},
        {"Ratskullz", ApLocationId.QuestRatskullz},
        {"Punk Rocker", ApLocationId.QuestPunkRocker},
        {"Photo Challenger Boy City", ApLocationId.QuestChallenge5},
        {"Photo Challenger Girl City", ApLocationId.QuestChallenge6},
        {"Office Director - Press-ing News", ApLocationId.QuestNews},
        {"Manhole", ApLocationId.QuestSewer},
        {"Hotbean Cart", ApLocationId.QuestHotbean},
        {"Hang in there buddy", ApLocationId.QuestHangInThere},
        {"Ghost Nature", ApLocationId.QuestScaryCity},
        {"Ghost Date", ApLocationId.QuestDate},
        {"Gallery Owner - Art Exhibition", ApLocationId.QuestArt},
        {"Food Influencer", ApLocationId.QuestInfluencer},
        {"Fashion Show - Design Problem", ApLocationId.QuestFashion},
        {"Cleaning away the stress", ApLocationId.QuestCleaning},
        {"Always Tumbled Granny", ApLocationId.QuestGranny},
        {"A Mouse Bakery", ApLocationId.QuestMice},
        {"A Thieving Crow", ApLocationId.QuestCrow},
        {"Yeti Cuteness", ApLocationId.QuestYetiCute},
        {"Wizard Inventor", ApLocationId.QuestIceWizard},
        {"Suspicious Activity - Military Base", ApLocationId.QuestMilitarySus},
        {"Play astronaut", ApLocationId.QuestAstronaut},
        {"Photo Challenger Boy Mountain", ApLocationId.QuestChallenge7},
        {"Photo Challenger Girl Mountain", ApLocationId.QuestChallenge8},
        {"Observatory Scientist", ApLocationId.QuestAsteroid},
        {"Goat Choir", ApLocationId.QuestGoatChoir},
        {"Snowball Memories", ApLocationId.QuestSnowball},
        {"Birthday Balloon In Distress", ApLocationId.QuestBirthday},
        {"Mountain Explorer", ApLocationId.QuestPaintings},
        {"Become a Yeti", ApLocationId.QuestBecomeYeti},
        {"Assemble a Snowman", ApLocationId.QuestSnowman},
        {"Bastu Balloons", ApLocationId.QuestBalloons},
        {"Treasure Hunter", ApLocationId.QuestArthur},
        {"Tangled Hair", ApLocationId.QuestBadHairDay},
        {"Take a nap", ApLocationId.QuestTakeANap},
        {"Spooky Story", ApLocationId.QuestSpookyStories},
        {"Painter - Closeup", ApLocationId.QuestPortraits},
        {"Nighttime Cinema", ApLocationId.QuestCinema},
        {"Night Lights", ApLocationId.QuestNightLights},
        {"Jetski Tricks", ApLocationId.QuestJetSki},
        {"Ice Cream Vendor", ApLocationId.QuestFruits},
        {"Ice Cream - Zombert", ApLocationId.QuestBrainFreeze},
        {"Ice Cream - Vampire", ApLocationId.QuestSweetTooth},
        {"Ice Cream - Prince", ApLocationId.QuestInYourFace},
        {"Ice Cream - Monkey", ApLocationId.QuestBrokenDreams},
        {"Dry Season", ApLocationId.QuestDrySeason},
        {"Dehydrated Muscles", ApLocationId.QuestMuscles},
        {"Castle Competition", ApLocationId.QuestSandCastle},
        {"Carnival Game", ApLocationId.QuestCarnival},
        {"Book of Bats", ApLocationId.QuestBats},
        {"Bitling Collector", ApLocationId.QuestBitling},
    };

    public static readonly Dictionary<string, ApLocationId> CreatureToApLocationId = new() {
        {"Cow", ApLocationId.CompCow},
        {"Flies", ApLocationId.CompFlies},
        {"Home Bird", ApLocationId.CompHomeBird},
        {"Tato", ApLocationId.CompTato},
        {"Ant", ApLocationId.CompAnt},
        {"Beehive", ApLocationId.CompBeehive},
        {"Butterfly", ApLocationId.CompButterfly},
        {"Oskar", ApLocationId.CompOskar},
        {"Sero", ApLocationId.CompSero},
        {"Forest Bird", ApLocationId.CompForestBird},
        {"Ladybug", ApLocationId.CompLadybug},
        {"Tom", ApLocationId.CompTom},
        {"Nestworm", ApLocationId.CompNestworm},
        {"Pet Rock", ApLocationId.CompPetRock},
        {"Snail", ApLocationId.CompSnail},
        {"Squirrel", ApLocationId.CompSquirrel},
        {"Stag Beetle", ApLocationId.CompStagBeetle},
        {"Tato Bug", ApLocationId.CompTatoBug},
        {"Tato Fly", ApLocationId.CompTatoFly},
        {"Bubble Fly", ApLocationId.CompBubbleFly},
        {"Fia", ApLocationId.CompFia},
        {"Fräs", ApLocationId.CompFras},
        {"Willemijn", ApLocationId.CompWillemijn},
        {"Crab", ApLocationId.CompCrab},
        {"Dragonfly", ApLocationId.CompDragonfly},
        {"Happy Carp", ApLocationId.CompHappyCarp},
        {"Jellyfish", ApLocationId.CompJellyfish},
        {"King Fish", ApLocationId.CompKingFish},
        {"Seagull", ApLocationId.CompSeagull},
        {"Seahorse", ApLocationId.CompSeahorse},
        {"Sunday Swan", ApLocationId.CompSundaySwan},
        {"Tato Scuba", ApLocationId.CompTatoScuba},
        {"Tato Swim", ApLocationId.CompTatoSwim},
        {"Toad", ApLocationId.CompToad},
        {"Business Pigeon", ApLocationId.CompBusinessPigeon},
        {"Portillo", ApLocationId.CompPortillo},
        {"Mouse", ApLocationId.CompMouse},
        {"Pigeon", ApLocationId.CompPigeon},
        {"Punky Parrot", ApLocationId.CompPunkParrot},
        {"Tato Skateboard", ApLocationId.CompTatoSkateboard},
        {"Tato Tourist", ApLocationId.CompTatoTourist},
        {"Turtle", ApLocationId.CompTurtle},
        {"Mikée", ApLocationId.CompMikee},
        {"Nariko", ApLocationId.CompNariko},
        {"Cosmo Deer", ApLocationId.CompCosmoDeer},
        {"Teddy", ApLocationId.CompTeddy},
        {"Fluff Ball", ApLocationId.CompFluff},
        {"Hedgehog", ApLocationId.CompHedgehog},
        {"Meteopal", ApLocationId.CompMeteopal},
        {"Mountain Goat", ApLocationId.CompGoat},
        {"Owl", ApLocationId.CompOwl},
        {"Snow Bird", ApLocationId.CompSnowBird},
        {"Tato Alien", ApLocationId.CompTatoAlien},
        {"Tato Ski", ApLocationId.CompTatoSki},
        {"Bat", ApLocationId.CompBat},
        {"Beach Snake", ApLocationId.CompSnake},
        {"Beak Bird", ApLocationId.CompBeakBird},
        {"Bitling Frog", ApLocationId.CompBitlingFrog},
        {"Bitling Mouse", ApLocationId.CompBitlingMouse},
        {"Bitling Snail", ApLocationId.CompBitlingSnail},
        {"Bitling Tato", ApLocationId.CompBitlingTato},
        {"Coco Crab", ApLocationId.CompCocoCrab},
        {"Day Lizard", ApLocationId.CompDayLizard},
        {"Drill Mole", ApLocationId.CompDrillMole},
        {"Eggert", ApLocationId.CompEggert},
        {"Fire Fly", ApLocationId.CompFireFly},
        {"Glow Worm", ApLocationId.CompGlowWorm},
        {"Itsy Bitsy", ApLocationId.CompItsyBitsy},
        {"Mud Frog", ApLocationId.CompMudFrog},
        {"Night Lizard", ApLocationId.CompNightLizard},
        {"Snout Bug", ApLocationId.CompSnoutBug},
        {"Tato Coco", ApLocationId.CompTatoCoco},
        {"Tato King", ApLocationId.CompTatoKing},
        {"Water Strider", ApLocationId.CompWaterStrider},
    };

    public static readonly Dictionary<string, ApLocationId> ItemToApLocationId = new() {
        {"Clogs", ApLocationId.ItemClogs},
        {"AwardMask", ApLocationId.ItemAwardMask},
        {"FoamFinger", ApLocationId.ItemFinger},
        {"Tripod", ApLocationId.ItemTripod},
        {"CowboyHat", ApLocationId.ItemCowboyHat},
        {"Pair of Socks", ApLocationId.ItemWetSocks},
        {"ScoutHat", ApLocationId.ItemFjallbjornHat},
        {"Sunglasses", ApLocationId.ItemGhostGlasses},
        {"Soaked Sock", ApLocationId.ItemSoakedSock},
        {"MonsterMask", ApLocationId.ItemMonsterMask},
        {"Camera Frames", ApLocationId.ItemFramesFilters},
        {"FishingHat", ApLocationId.ItemFishingHat},
        {"Honk", ApLocationId.ItemHonkAttachment},
        {"Umbrella", ApLocationId.ItemUmbrella},
        {"Pirate Key", ApLocationId.ItemOldKey},
        {"Hardhat", ApLocationId.ItemHardHat},
        {"DiverHelmet", ApLocationId.ItemDivingHelmet},
        {"Rubber Boots", ApLocationId.ItemRubberBoots},
        {"SupremeSandwich", ApLocationId.ItemSandwich},
        {"PirateHat", ApLocationId.ItemPirateHat},
        {"PaperHat", ApLocationId.ItemPaperHat},
        {"PhotoFlag", ApLocationId.ItemFlag},
        {"Hotbean Hat", ApLocationId.ItemHotbeanHat},
        {"ReporterHat", ApLocationId.ItemReporterHat},
        {"Sneakers", ApLocationId.ItemSneakers},
        {"Cinnamonbun", ApLocationId.ItemCinnamonBun},
        {"Frisbee", ApLocationId.ItemFrisbee},
        {"Snow Boots", ApLocationId.ItemClimbingBoots},
        {"Puff Hat", ApLocationId.ItemPufferHat},
        {"Scarf", ApLocationId.ItemScarf},
        {"SkiGoggles", ApLocationId.ItemSkiGoggles},
        {"SpaceHelmet", ApLocationId.ItemSpaceHelmet},
        {"Bastu Ticket", ApLocationId.ItemBastoTicket},
        {"Water Balloon", ApLocationId.ItemWatergun},
        {"Sunhat", ApLocationId.ItemSunHat},
        {"Fruit Pear", ApLocationId.ItemMelonear},
        {"Fruit Banana", ApLocationId.ItemBanakin},
        {"Fruit Orange", ApLocationId.ItemOranganas},
        {"Fruit Bean", ApLocationId.ItemBeanut},
        {"Pickaxe", ApLocationId.ItemPickaxe},
        {"Suncap", ApLocationId.ItemSunCap},
        {"Flipflops", ApLocationId.ItemFlipFlops},
        {"Ice Cream", ApLocationId.ItemIceCreamBanakin},
        {"Royal Cape", ApLocationId.ItemRoyalCape},
        {"MiniGame Ticket", ApLocationId.ItemMinigameTicket},
        {"Lei", ApLocationId.ItemLei},
        {"Vacation Shirt", ApLocationId.ItemVacationShirt},
        {"Royal Cane", ApLocationId.ItemRoyalCane},
        {"Water Bottle Empty", ApLocationId.ItemEmptyBottle},
        {"Viking Helmet", ApLocationId.ItemVikingHelmet},
        {"Foot Cast", ApLocationId.ItemFootCast},
        {"Beret", ApLocationId.ItemBeret},
        {"Crown", ApLocationId.ItemRoyalCrown},
    };
    
    public static readonly Dictionary<string, ApLocationId> CassetteToApLocationId = new() {
        //{"Jamal Green - Everybody That You Meet", ApLocationId.TapeEverybody}, // Not obtainable?
        { "Jamal Green - Photo of Home ", ApLocationId.TapePhotoOfHome},
        {"Jamal Green - Summer Breeze", ApLocationId.TapeSummerBreeze},
        {"Jamal Green - The Grand Squirrel Hotel", ApLocationId.TapeSquirrelHotel},
        {"Launchable Socks - Pine Needles", ApLocationId.TapePineNeedles},
        {"Launchable Socks - Squirrel Photography", ApLocationId.TapeSquirrelPhoto},
        {"Fisherman's Whistle", ApLocationId.TapeFishermansWhistle},
        {"JG+LS - The Smiling Huntsman", ApLocationId.TapeSmilingHuntsman},
        {"Jamal Green - NAUT", ApLocationId.TapeNaut},
        {"Launchable Socks - A Place In The Sun", ApLocationId.TapePlaceInSun},
        {"Launchable Socks - Fisherman's Tune", ApLocationId.TapeFishermansTune},
        {"Anes Sabanovic - Ratskullz Theme", ApLocationId.TapeRatskullzTheme},
        {"JG+LS - The Big City", ApLocationId.TapeBigCity},
        {"Jamal Green - Hustle Bustle Shuffle", ApLocationId.TapeHustleBustle},
        {"Launchable Socks - Hop Skip Step", ApLocationId.TapeHopSkipStep},
        {"Launchable Socks - On The Hour", ApLocationId.TapeOnTheHour},
        {"Jamal Green - Life Through a Lens", ApLocationId.TapeLifeThroughLens},
        {"Jamal Green - The Petting of a Sacred Deer", ApLocationId.TapePettingDeer},
        //{"Launchable Socks - G.O.A.T Choir", ApLocationId.TapeGoatChoir}, // Not obtainable?
        {"Launchable Socks - Stories Of Snow", ApLocationId.TapeStoriesOfSnow},
        //{"Launchable Socks - TOEM", ApLocationId.TapeToem}, // Not obtainable?
        {"Launchable Socks - Tall & Shy", ApLocationId.TapeTallShy},
        {"JG+LS - Night Jam", ApLocationId.TapeNightJam},
        {"Jamal Green - A Warm Days Night", ApLocationId.TapeWarmDaysNight},
        {"Jamal Green - One By One", ApLocationId.TapeOneByOne},
        {"Launchable Socks - Hammock Days", ApLocationId.TapeHammockDays},
        {"Launchable Socks - Sailor's Tune", ApLocationId.TapeSailorsTune},
        {"Launchable Socks - Song Of The Sea", ApLocationId.TapeSongOfTheSea},
    };

    public static readonly Dictionary<string, ApLocationId> CheevoToApLocationId = new() {
        {"Start Your Adventure", ApLocationId.CheevoBeginning},
        {"Sight Photo Home House", ApLocationId.CheevoHomeSweetHome},
        {"Visit Forest", ApLocationId.CheevoCalmForest},
        {"Sight Photo Forest OakHotel", ApLocationId.CheevoMajesticHotel},
        {"Endore snail race", ApLocationId.CheevoSlowAndSteady},
        {"Photo Challenges Forest", ApLocationId.CheevoNatureShowstopper},
        {"Quest Region Forest", ApLocationId.CheevoStrongAsAnOak},
        {"Close Up Sune The Skeleton", ApLocationId.CheevoCalmedDown},
        {"Close Up Sockman", ApLocationId.CheevoJustASock},
        {"Hotel Easter Egg", ApLocationId.CheevoYouFoundUs},
        {"Visit Harbor", ApLocationId.CheevoSetSail},
        {"Sight Photo Harbor Shipwerck", ApLocationId.CheevoVoyageUnderwater},
        {"Employee Of The Month Award", ApLocationId.CheevoEmployeeOfTheMonth},
        {"Photo Challenges Harbor", ApLocationId.CheevoCalmAsSea},
        {"Quest Region Harbor", ApLocationId.CheevoSeaworthy},
        {"Close Up Seagull", ApLocationId.CheevoFlightReady},
        {"Close Up Dancer", ApLocationId.CheevoSparklingJump},
        {"Pet a pet", ApLocationId.CheevoGoodBoy},
        {"Visit City", ApLocationId.CheevoBigCity},
        {"Sight Photo City Grand Clock Tower", ApLocationId.CheevoClocktower},
        {"Photo Challenges City", ApLocationId.CheevoProfessional},
        {"Quest Region City", ApLocationId.CheevoBusiness},
        {"Close Up Food Influencer", ApLocationId.CheevoFollowers},
        {"Close Up Stressed Human", ApLocationId.CheevoNewJob},
        {"Visit Mountain", ApLocationId.CheevoSnowyPeaks},
        {"Equip Full Snowsuit", ApLocationId.CheevoGearedUp},
        {"Photo Challenges Mountain", ApLocationId.CheevoHurdle},
        {"Quest Region Mountain", ApLocationId.CheevoFighter},
        {"Close Up Old Man", ApLocationId.CheevoYouth},
        {"Close Up Mountain Explorer", ApLocationId.CheevoStory},
        {"Visit Mountain Top", ApLocationId.CheevoClose},
        {"Sight Photo Mountain TOEM", ApLocationId.CheevoToem},
        {"Photograph the teams pets", ApLocationId.CheevoCuties},
        {"Base Game Compendium", ApLocationId.CheevoCollectEmAll},
        {"Walking with clogs", ApLocationId.CheevoGoingLong},
        {"Equip All Items Once", ApLocationId.CheevoCosplayer},
        {"Complete All Quests", ApLocationId.CheevoCompletionist},
        {"Visit Resort", ApLocationId.CheevoTropicalParadise},
        {"Vacation Mode", ApLocationId.CheevoMaximumVacation},
        {"Close Up King", ApLocationId.CheevoKingsShirt},
        {"Close Up Naked", ApLocationId.CheevoMoonlitBeauty},
        {"Close Up Player", ApLocationId.CheevoSelfPortrait},
        {"Cool Moon", ApLocationId.CheevoWazzuuppp},
        {"Play Everything At The Carnival", ApLocationId.CheevoProGamer},
        {"Take a splash", ApLocationId.CheevoSplishSplash},
        {"Sight Photo Resort", ApLocationId.CheevoRoyalCastle},
        {"Resort Compendium", ApLocationId.CheevoSomeMore},
        {"Quest Region Resort", ApLocationId.CheevoVikingsHoliday},
    };

    public static readonly Dictionary<ApLocationId, ApItemId> ApLocationIdToApItemId = new() {
        {ApLocationId.ItemClogs, ApItemId.Clogs},
        {ApLocationId.ItemAwardMask, ApItemId.AwardMask},
        {ApLocationId.ItemFinger, ApItemId.Finger},
        {ApLocationId.ItemTripod, ApItemId.Tripod},
        {ApLocationId.ItemCowboyHat, ApItemId.CowboyHat},
        {ApLocationId.ItemWetSocks, ApItemId.WetSocks},
        {ApLocationId.ItemFjallbjornHat, ApItemId.FjallbjornHat},
        {ApLocationId.ItemGhostGlasses, ApItemId.GhostGlasses},
        {ApLocationId.ItemSoakedSock, ApItemId.SoakedSock},
        {ApLocationId.ItemMonsterMask, ApItemId.MonsterMask},
        {ApLocationId.ItemFramesFilters, ApItemId.FramesFilters},
        {ApLocationId.ItemFishingHat, ApItemId.FishingHat},
        {ApLocationId.ItemHonkAttachment, ApItemId.HonkAttachment},
        {ApLocationId.ItemUmbrella, ApItemId.Umbrella},
        {ApLocationId.ItemOldKey, ApItemId.OldKey},
        {ApLocationId.ItemHardHat, ApItemId.HardHat},
        {ApLocationId.ItemDivingHelmet, ApItemId.DivingHelmet},
        {ApLocationId.ItemRubberBoots, ApItemId.RubberBoots},
        {ApLocationId.ItemSandwich, ApItemId.Sandwich},
        {ApLocationId.ItemPirateHat, ApItemId.PirateHat},
        {ApLocationId.ItemPaperHat, ApItemId.PaperHat},
        {ApLocationId.ItemFlag, ApItemId.Flag},
        {ApLocationId.ItemHotbeanHat, ApItemId.HotbeanHat},
        {ApLocationId.ItemReporterHat, ApItemId.ReporterHat},
        {ApLocationId.ItemSneakers, ApItemId.Sneakers},
        {ApLocationId.ItemCinnamonBun, ApItemId.CinnamonBun},
        {ApLocationId.ItemFrisbee, ApItemId.Frisbee},
        {ApLocationId.ItemClimbingBoots, ApItemId.ClimbingBoots},
        {ApLocationId.ItemPufferHat, ApItemId.PufferHat},
        {ApLocationId.ItemScarf, ApItemId.Scarf},
        {ApLocationId.ItemSkiGoggles, ApItemId.SkiGoggles},
        {ApLocationId.ItemSpaceHelmet, ApItemId.SpaceHelmet},
        {ApLocationId.ItemBastoTicket, ApItemId.BastoTicket},
        {ApLocationId.ItemWatergun, ApItemId.Watergun},
        {ApLocationId.ItemSunHat, ApItemId.SunHat},
        {ApLocationId.ItemMelonear, ApItemId.Melonear},
        {ApLocationId.ItemBanakin, ApItemId.Banakin},
        {ApLocationId.ItemOranganas, ApItemId.Oranganas},
        {ApLocationId.ItemBeanut, ApItemId.Beanut},
        {ApLocationId.ItemPickaxe, ApItemId.Pickaxe},
        {ApLocationId.ItemSunCap, ApItemId.SunCap},
        {ApLocationId.ItemFlipFlops, ApItemId.FlipFlops},
        {ApLocationId.ItemIceCreamBanakin, ApItemId.IceCream},
        {ApLocationId.ItemIceCreamMelonear, ApItemId.IceCream},
        {ApLocationId.ItemIceCreamBeanut, ApItemId.IceCream},
        {ApLocationId.ItemIceCreamOranganas, ApItemId.IceCream},
        {ApLocationId.ItemRoyalCape, ApItemId.RoyalCape},
        {ApLocationId.ItemMinigameTicket, ApItemId.MinigameTicket},
        {ApLocationId.ItemLei, ApItemId.Lei},
        {ApLocationId.ItemVacationShirt, ApItemId.VacationShirt},
        {ApLocationId.ItemRoyalCane, ApItemId.RoyalCane},
        {ApLocationId.ItemEmptyBottle, ApItemId.EmptyBottle},
        {ApLocationId.ItemVikingHelmet, ApItemId.VikingHelmet},
        {ApLocationId.ItemFootCast, ApItemId.FootCast},
        {ApLocationId.ItemBeret, ApItemId.Beret},
        {ApLocationId.ItemRoyalCrown, ApItemId.RoyalCrown},
        // Cassettes
        {ApLocationId.TapePhotoOfHome, ApItemId.PhotoOfHomeTape},
        {ApLocationId.TapeSummerBreeze, ApItemId.SummerBreezeTape},
        {ApLocationId.TapeSquirrelHotel, ApItemId.SquirrelHotelTape},
        {ApLocationId.TapePineNeedles, ApItemId.PineNeedlesTape},
        {ApLocationId.TapeSquirrelPhoto, ApItemId.SquirrelPhotoTape},
        {ApLocationId.TapeFishermansWhistle, ApItemId.FishermansWhistleTape},
        {ApLocationId.TapeSmilingHuntsman, ApItemId.SmilingHuntsmanTape},
        {ApLocationId.TapeNaut, ApItemId.NautTape},
        {ApLocationId.TapePlaceInSun, ApItemId.PlaceInSunTape},
        {ApLocationId.TapeFishermansTune, ApItemId.FishermansTuneTape},
        {ApLocationId.TapeRatskullzTheme, ApItemId.RatskullzThemeTape},
        {ApLocationId.TapeBigCity, ApItemId.BigCityTape},
        {ApLocationId.TapeHustleBustle, ApItemId.HustleBustleTape},
        {ApLocationId.TapeHopSkipStep, ApItemId.HopSkipStepTape},
        {ApLocationId.TapeOnTheHour, ApItemId.OnTheHourTape},
        {ApLocationId.TapeLifeThroughLens, ApItemId.LifeThroughLensTape},
        {ApLocationId.TapePettingDeer, ApItemId.PettingDeerTape},
        {ApLocationId.TapeStoriesOfSnow, ApItemId.StoriesOfSnowTape},
        {ApLocationId.TapeTallShy, ApItemId.TallShyTape},
        {ApLocationId.TapeNightJam, ApItemId.NightJamTape},
        {ApLocationId.TapeWarmDaysNight, ApItemId.WarmDaysNightTape},
        {ApLocationId.TapeOneByOne, ApItemId.OneByOneTape},
        {ApLocationId.TapeHammockDays, ApItemId.HammockDaysTape},
        {ApLocationId.TapeSailorsTune, ApItemId.SailorsTuneTape},
        {ApLocationId.TapeSongOfTheSea, ApItemId.SongOfTheSeaTape},
    };

    public static readonly Dictionary<ApItemId, Quest.QuestRegion> ApItemIdToQuestRegion = new() {
        {ApItemId.StampHomelanda, Quest.QuestRegion.Home},
        {ApItemId.StampOaklaville, Quest.QuestRegion.Forest},
        {ApItemId.StampStanhamn, Quest.QuestRegion.Harbor},
        {ApItemId.StampLogcity, Quest.QuestRegion.City},
        {ApItemId.StampKiiruberg, Quest.QuestRegion.Mountain},
        {ApItemId.StampBasto, Quest.QuestRegion.Resort},
        {ApItemId.ProgressiveStamp, Quest.QuestRegion.Generic},
    };
    
    public static readonly Dictionary<ApItemId, string> ApItemIdToItem = new() {
        {ApItemId.Clogs, "Clogs"},
        {ApItemId.AwardMask, "AwardMask"},
        {ApItemId.Finger, "FoamFinger"},
        {ApItemId.Tripod, "Tripod"},
        {ApItemId.CowboyHat, "CowboyHat"},
        {ApItemId.WetSocks, "Pair of Socks"},
        {ApItemId.FjallbjornHat, "ScoutHat"},
        {ApItemId.GhostGlasses, "Sunglasses"},
        {ApItemId.SoakedSock, "Soaked Sock"},
        {ApItemId.MonsterMask, "MonsterMask"},
        {ApItemId.FramesFilters, "Camera Frames"},
        {ApItemId.FishingHat, "FishingHat"},
        {ApItemId.HonkAttachment, "Honk"},
        {ApItemId.Umbrella, "Umbrella"},
        {ApItemId.OldKey, "Pirate Key"},
        {ApItemId.HardHat, "Hardhat"},
        {ApItemId.DivingHelmet, "DiverHelmet"},
        {ApItemId.RubberBoots, "Rubber Boots"},
        {ApItemId.Sandwich, "SupremeSandwich"},
        {ApItemId.PirateHat, "PirateHat"},
        {ApItemId.PaperHat, "PaperHat"},
        {ApItemId.Flag, "PhotoFlag"},
        {ApItemId.HotbeanHat, "Hotbean Hat"},
        {ApItemId.ReporterHat, "ReporterHat"},
        {ApItemId.Sneakers, "Sneakers"},
        {ApItemId.CinnamonBun, "Cinnamonbun"},
        {ApItemId.Frisbee, "Frisbee"},
        {ApItemId.ClimbingBoots, "Snow Boots"},
        {ApItemId.PufferHat, "Puff Hat"},
        {ApItemId.Scarf, "Scarf"},
        {ApItemId.SkiGoggles, "SkiGoggles"},
        {ApItemId.SpaceHelmet, "SpaceHelmet"},
        {ApItemId.BastoTicket, "Bastu Ticket"},
        {ApItemId.Watergun, "Water Balloon Popper Attachment"},
        {ApItemId.SunHat, "Sunhat"},
        {ApItemId.Melonear, "Fruit Pear"},
        {ApItemId.Banakin, "Fruit Banana"},
        {ApItemId.Oranganas, "Fruit Orange"},
        {ApItemId.Beanut, "Fruit Bean"},
        {ApItemId.Pickaxe, "Pickaxe"},
        {ApItemId.SunCap, "Suncap"},
        {ApItemId.FlipFlops, "Flipflops"},
        {ApItemId.IceCream, "Ice Cream"},
        {ApItemId.RoyalCape, "Royal Cape"},
        {ApItemId.MinigameTicket, "MiniGame Ticket"},
        {ApItemId.Lei, "Lei"},
        {ApItemId.VacationShirt, "Vacation Shirt"},
        {ApItemId.RoyalCane, "Royal Cane"},
        {ApItemId.EmptyBottle, "Water Bottle Empty"},
        {ApItemId.VikingHelmet, "Viking Helmet"},
        {ApItemId.FootCast, "Foot Cast"},
        {ApItemId.Beret, "Beret"},
        {ApItemId.RoyalCrown, "Royal Crown"},
        // Cassettes
        {ApItemId.PhotoOfHomeTape, "Jamal Green - Photo of Home "},
        {ApItemId.SummerBreezeTape, "Jamal Green - Summer Breeze"},
        {ApItemId.SquirrelHotelTape, "Jamal Green - The Grand Squirrel Hotel"},
        {ApItemId.PineNeedlesTape, "Launchable Socks - Pine Needles"},
        {ApItemId.SquirrelPhotoTape, "Launchable Socks - Squirrel Photography"},
        {ApItemId.FishermansWhistleTape, "Fisherman's Whistle"},
        {ApItemId.SmilingHuntsmanTape, "JG+LS - The Smiling Huntsman"},
        {ApItemId.NautTape, "Jamal Green - Naut"},
        {ApItemId.PlaceInSunTape, "Launchable Socks - A Place In The Sun"},
        {ApItemId.FishermansTuneTape, "Launchable Socks - Fisherman's Tune"},
        {ApItemId.RatskullzThemeTape, "Anes Sabanovic - Ratskullz Theme"},
        {ApItemId.BigCityTape, "JG+LS - The Big City"},
        {ApItemId.HustleBustleTape, "Jamal Green - Hustle Bustle Shuffle"},
        {ApItemId.HopSkipStepTape, "Launchable Socks - Hop Skip Step"},
        {ApItemId.OnTheHourTape, "Launchable Socks - On The Hour"},
        {ApItemId.LifeThroughLensTape, "Jamal Green - Life Through a Lens"},
        {ApItemId.PettingDeerTape, "Jamal Green - The Petting of a Sacred Deer "},
        {ApItemId.StoriesOfSnowTape, "Launchable Socks - Stories Of Snow"},
        {ApItemId.TallShyTape, "Launchable Socks - Tall & Shy"},
        {ApItemId.NightJamTape, "JG+LS - Night Jam"},
        {ApItemId.WarmDaysNightTape, "Jamal Green - A Warm Days Night"},
        {ApItemId.OneByOneTape, "Jamal Green - One By One"},
        {ApItemId.HammockDaysTape, "Launchable Socks - Hammock Days"},
        {ApItemId.SailorsTuneTape, "Launchable Socks - Sailor's Tune"},
        {ApItemId.SongOfTheSeaTape, "Launchable Socks - Song Of The Sea"},
    };
    
    public static readonly Dictionary<string, string> RegionSceneName = new() {
        {"home", "Home"},
        {"forest", "Forest"},
        {"harbor", "Harbor"},
        {"city", "City"},
        {"mountainTop", "MountainTop"},
        {"mountain", "Mountain"},
        {"resort", "Resort"},
    };
    
    // Note that the transition uses the vanilla target scene not the exiting scene
    public static readonly Dictionary<string, Dictionary<int, ApConnectionId>> SceneTransitionToEntrance = new() {
        {"homeRoomPlayer", new() {{1, ApConnectionId.PlayerRoomEntrance}}},
        {"homeRoomLiving", new() {{1, ApConnectionId.PlayerRoomExit}, {2, ApConnectionId.HomelandaHouseEntrance}}},
        {"homeHouse", new() {{2, ApConnectionId.HomelandaHouseExit}}},
        {"forestBusStop", new() {{0, ApConnectionId.OutsideHotelDown}}},
        {"forestHotel", new() {{0, ApConnectionId.OaklavilleBusStopExit}, {20, ApConnectionId.HotelExit},
            {1, ApConnectionId.GhostCupGameRight}, {2, ApConnectionId.ScoutCampLeft}}},
        {"forestHotelInside", new() {{20, ApConnectionId.HotelEntrance}, {33, ApConnectionId.HotelElevatorExit}}},
        {"forestHotelElevator", new() {{33, ApConnectionId.HotelElevatorEntrance}}},
        {"forestHideIntersection", new() {{1, ApConnectionId.OutsideHotelLeft},
            {2, ApConnectionId.HideAndSeekRight}, {20, ApConnectionId.MushroomHouseExit}}},
        {"forestMushroomInside", new() {{20, ApConnectionId.MushroomHouseEntrance}}},
        {"forestHideAndSeek", new() {{2, ApConnectionId.GhostCupGameLeft}, {5, ApConnectionId.GraveyardRight}}},
        {"forestGraveyard", new() {{5, ApConnectionId.HideAndSeekLeft}, 
            {12, ApConnectionId.SkeletonHouseExit}, {41, ApConnectionId.SkeletonHouseBalconyExit}}},
        {"forestGraveyardInside", new() {{12, ApConnectionId.SkeletonHouseEntrance}, {41, ApConnectionId.SkeletonHouseBalconyEntrance}}},
        {"forestCamp", new() {{2, ApConnectionId.OutsideHotelRight}, 
            {10, ApConnectionId.OaklavilleTrailDown}, {5, ApConnectionId.PlaygroundLeft}}},
        {"forestTrail0", new() {{10, ApConnectionId.ScoutCampUp}, {1, ApConnectionId.LookoutExit}}},
        {"forestTrail1", new() {{1, ApConnectionId.OaklavilleTrailUp}}},
        {"forestPlayground", new() {{5, ApConnectionId.ScoutCampRight}, {13, ApConnectionId.OutsideRaveLeft}}},
        {"forestRaveIntersection", new() {{13, ApConnectionId.PlaygroundRight}, {5, ApConnectionId.RaveExit}}},
        {"forestRave", new() {{5, ApConnectionId.RaveEntrance}}},
        {"harborBusStop", new() {{10, ApConnectionId.PhotoGuildHutExit}, 
            {5, ApConnectionId.PirateDrawbridgeRight}, {2, ApConnectionId.DocksLeftExit}}},
        {"harborPhotoGuildInside", new() {{10, ApConnectionId.PhotoGuildHutEntrance}}},
        {"harborBridgeBeachCentrum", new() {{5, ApConnectionId.StanhamnBusStopLeft}, {1, ApConnectionId.HippoBeachRight}}},
        {"harborBeach", new() {{1, ApConnectionId.PirateDrawbridgeLeft}, 
            {9, ApConnectionId.UnderwaterExit}, {2, ApConnectionId.OutsideLighthouseRight}}},
        {"harborUnderwater", new() {{9, ApConnectionId.HippoBeachManhole}}},
        {"harborHonkhouse", new() {{2, ApConnectionId.HippoBeachLeft}, 
            {80, ApConnectionId.LighthouseExit}, {1, ApConnectionId.KingFishBeachExit}}},
        {"harborHonkHouseInside", new() {{80, ApConnectionId.LighthouseEntrance}, {8, ApConnectionId.LighthouseRoofExit}}},
        {"harborHonkHouseTop", new() {{8, ApConnectionId.LighthouseRoofEntrance}}},
        {"harborCliffs", new() {{1, ApConnectionId.OutsideLighthouseUp}}},
        {"harborDocks", new() {{2, ApConnectionId.StanhamnBusStopRight}, {1, ApConnectionId.FishingTowerLeft}}},
        {"harborFishingTower", new() {{1, ApConnectionId.DocksRightExit}, {2, ApConnectionId.GhostDrawbridgeDown}}},
        {"harborBridgeFishingHydro", new() {{2, ApConnectionId.FishingTowerUp}, {5, ApConnectionId.OutsideHydroplantRight}}},
        {"harborHydroplant", new() {{5, ApConnectionId.GhostDrawbridgeLeft}, {8, ApConnectionId.HydroplantExit}}},
        {"harborHydroplant_Inside", new() {{8, ApConnectionId.HydroplantEntrance}}},
        {"cityBusStop", new() {{1, ApConnectionId.LogcityBusStopEntrance}}},
        {"cityHub", new() {{8, ApConnectionId.CrossWalkRight}, {4, ApConnectionId.OutsideCafeLeft}, 
            {1, ApConnectionId.EscalatorUp}, {3, ApConnectionId.OutsideFashionShowDown}}},
        {"cityParking", new() {{8, ApConnectionId.ClockTowerLeft}, {1, ApConnectionId.OverpassDown}}},
        {"cityOverpass", new() {{4, ApConnectionId.OutsideFashionShowLeft}, {1, ApConnectionId.CrossWalkUp},
            {3, ApConnectionId.SkateParkDown}, {15, ApConnectionId.NewsHouseExit}}},
        {"cityNewsHouseInside", new() {{15, ApConnectionId.NewsHouseEntrance}}},
        {"citySkateboard", new() {{3, ApConnectionId.OverpassUp}, {1, ApConnectionId.RatskullzAlleyExit}, {500, ApConnectionId.OutsideCafeTaxi}}},
        {"cityAlley", new() {{1, ApConnectionId.SkateParkRight}}},
        {"cityBigTown", new() {{4, ApConnectionId.OverpassRight}, {3, ApConnectionId.ClockTowerUp},
            {2, ApConnectionId.OutsideGalleryShowLeft}, {20, ApConnectionId.FashionShowExit}}},
        {"cityFashionShow", new() {{20, ApConnectionId.FashionShowEntrance}, {201, ApConnectionId.FashionShowBackstageExit}}},
        {"cityFashionShowBackstage", new() {{201, ApConnectionId.FashionShowBackstageEntrance}}},
        {"cityCafe", new() {{4, ApConnectionId.ClockTowerRight}, {5, ApConnectionId.OutsideGalleryShowDown},
            {500, ApConnectionId.SkateParkTaxi}, {200, ApConnectionId.CafeExit}}},
        {"cityCafeInside", new() {{200, ApConnectionId.CafeEntrance}}},
        {"cityGallery", new() {{5, ApConnectionId.OutsideCafeUp},
            {2, ApConnectionId.OutsideFashionShowRight}, {6, ApConnectionId.GalleryExit}}},
        {"cityGalleryInside", new() {{6, ApConnectionId.GalleryEntrance}}},
        {"mountainBusStop", new() {{1, ApConnectionId.BirthdayPartyDown}}},
        {"mountainTown", new() {{3, ApConnectionId.SkiLiftBaseLeft}, {4, ApConnectionId.FrozenPondRight},
            {2, ApConnectionId.SnowmanSquareDown}, {1, ApConnectionId.KiirubergBusStopUp}, {23, ApConnectionId.BalloonHouseExit}}},
        {"mountainTownInside", new() {{23, ApConnectionId.BalloonHouseEntrance}}},
        {"mountainLakeLonely", new() {{4, ApConnectionId.BirthdayPartyLeft}, {8, ApConnectionId.OldMansHouseExit}}},
        {"mountainOldManInside", new() {{8, ApConnectionId.OldMansHouseEntrance}}},
        {"mountainTown2", new() {{2, ApConnectionId.BirthdayPartyUp}, {8, ApConnectionId.OutsideWizardTowerRight},
            {5, ApConnectionId.CliffsDown}, {80, ApConnectionId.MecksHouseExit}, {100, ApConnectionId.MilitaryBaseExit}}},
        {"mountainMilitary", new() {{100, ApConnectionId.MilitaryBaseEntrance}}},
        {"mountainMeckInside", new() {{80, ApConnectionId.MecksHouseEntrance}}},
        {"mountainWizard", new() {{8, ApConnectionId.SnowmanSquareLeft}, {99, ApConnectionId.WizardTowerExit}}},
        {"mountainWizardInside", new() {{99, ApConnectionId.WizardTowerEntrance}, {999, ApConnectionId.WizardPortalExit}}},
        {"CosmoGarden", new() {{999, ApConnectionId.WizardPortalEntrance}}},
        {"mountainCliff", new() {{5, ApConnectionId.SnowmanSquareUp},
            {1, ApConnectionId.OutsideObservatoryDown}, {2, ApConnectionId.BlizzardBridgeLeft}}},
        {"mountainWindyLobby", new() {{2, ApConnectionId.CliffsRight},
            {3, ApConnectionId.BlizzardMonsterExit}, {200, ApConnectionId.ManCaveExit}}},
        {"mountainManCave", new() {{200, ApConnectionId.ManCaveEntrance}}},
        {"mountainWindyEnd", new() {{3, ApConnectionId.BlizzardBridgeRight}}},
        {"mountainObservatoryTop", new() {{1, ApConnectionId.CliffsUp},
            {2, ApConnectionId.SkiMountainTopLeft}, {40, ApConnectionId.ObservatoryExit}}},
        {"mountainObservatory", new() {{40, ApConnectionId.ObservatoryEntrance}}},
        {"mountainSkiCabin", new() {{3, ApConnectionId.BirthdayPartyRight}, {9, ApConnectionId.SkiLodgeExit}}},
        {"mountainSkiCabinInside", new() {{9, ApConnectionId.SkiLodgeEntrance}}},
        {"mountainSkiTop", new() {{2, ApConnectionId.OutsideObservatoryRight}}},
        {"mountainTop", new() {{0, ApConnectionId.ToemDescend}}},
        {"mountainTopToem", new() {{0, ApConnectionId.MountainTopBusStopClimb}}},
        {"resortBusstop", new() {{1, ApConnectionId.LilyPadPondDown}}},
        {"resortCenter", new() {{1, ApConnectionId.BastoHarborUp}, {4, ApConnectionId.OutsideCastleDown},
            {3, ApConnectionId.GhostHangoutLeft}, {2, ApConnectionId.CampsiteRight}}},
        {"resortNana", new() {{2, ApConnectionId.LilyPadPondLeft}, {10, ApConnectionId.TentExit}}},
        {"resortHomeTent", new() {{10, ApConnectionId.TentEntrance}}},
        {"resortCastle", new() {{4, ApConnectionId.LilyPadPondUp}, {2, ApConnectionId.CastleExit},
            {20, ApConnectionId.GymHouseExit}, {5, ApConnectionId.BonfireLowerRight}}},
        {"resortCastleInside", new() {{2, ApConnectionId.CastleEntrance}}},
        {"resortDrinkInside", new() {{20, ApConnectionId.GymHouseEntrance}}},
        {"resortDino", new() {{5, ApConnectionId.OutsideCastleLeft}, {7, ApConnectionId.CarnivalExit}, {12, ApConnectionId.JungleLeft}}},
        {"resortCarnivalInside", new() {{7, ApConnectionId.CarnivalEntrance}}},
        {"resortGhost", new() {{3, ApConnectionId.LilyPadPondRight}, {40, ApConnectionId.GhostHangoutCaveExit}}},
        {"resortCaveTrail", new() {{40, ApConnectionId.GhostHangoutCaveEntrance},
            {10, ApConnectionId.SecretCaveRoomExit}, {41, ApConnectionId.JungleCaveEntrance}}},
        {"resortSecretCave", new() {{10, ApConnectionId.SecretCaveRoomEntrance}}},
        {"resortJungle", new() {{41, ApConnectionId.JungleCaveExit}, {12, ApConnectionId.BonfireUpperRight}}},
    };

    public static readonly Dictionary<ApConnectionId, Tuple<string, int>> EntranceToSceneTransition = new() {
        {ApConnectionId.PlayerRoomExit, Tuple.Create("homeRoomPlayer", 1)},
        {ApConnectionId.PlayerRoomEntrance, Tuple.Create("homeRoomLiving", 1)},
        {ApConnectionId.HomelandaHouseExit, Tuple.Create("homeRoomLiving", 2)},
        {ApConnectionId.HomelandaHouseEntrance, Tuple.Create("homeHouse", 2)},
        {ApConnectionId.OaklavilleBusStopExit, Tuple.Create("forestBusStop", 0)},
        {ApConnectionId.OutsideHotelDown, Tuple.Create("forestHotel", 0)},
        {ApConnectionId.OutsideHotelLeft, Tuple.Create("forestHotel", 1)},
        {ApConnectionId.OutsideHotelRight, Tuple.Create("forestHotel", 2)},
        {ApConnectionId.HotelEntrance, Tuple.Create("forestHotel", 20)},
        {ApConnectionId.HotelExit, Tuple.Create("forestHotelInside", 20)},
        {ApConnectionId.HotelElevatorEntrance, Tuple.Create("forestHotelInside", 33)},
        {ApConnectionId.HotelElevatorExit, Tuple.Create("forestHotelElevator", 33)},
        {ApConnectionId.GhostCupGameRight, Tuple.Create("forestHideIntersection", 1)},
        {ApConnectionId.MushroomHouseEntrance, Tuple.Create("forestHideIntersection", 20)},
        {ApConnectionId.GhostCupGameLeft, Tuple.Create("forestHideIntersection", 2)},
        {ApConnectionId.MushroomHouseExit, Tuple.Create("forestMushroomInside", 20)},
        {ApConnectionId.HideAndSeekRight, Tuple.Create("forestHideAndSeek", 2)},
        {ApConnectionId.HideAndSeekLeft, Tuple.Create("forestHideAndSeek", 5)},
        {ApConnectionId.GraveyardRight, Tuple.Create("forestGraveyard", 5)},
        {ApConnectionId.SkeletonHouseEntrance, Tuple.Create("forestGraveyard", 12)},
        {ApConnectionId.SkeletonHouseExit, Tuple.Create("forestGraveyardInside", 12)},
        {ApConnectionId.SkeletonHouseBalconyExit, Tuple.Create("forestGraveyardInside", 41)},
        {ApConnectionId.SkeletonHouseBalconyEntrance, Tuple.Create("forestGraveyard", 41)},
        {ApConnectionId.ScoutCampLeft, Tuple.Create("forestCamp", 2)},
        {ApConnectionId.ScoutCampUp, Tuple.Create("forestCamp", 10)},
        {ApConnectionId.ScoutCampRight, Tuple.Create("forestCamp", 5)},
        {ApConnectionId.OaklavilleTrailUp, Tuple.Create("forestTrail0", 1)},
        {ApConnectionId.OaklavilleTrailDown, Tuple.Create("forestTrail0", 10)},
        {ApConnectionId.LookoutExit, Tuple.Create("forestTrail1", 1)},
        {ApConnectionId.PlaygroundLeft, Tuple.Create("forestPlayground", 5)},
        {ApConnectionId.PlaygroundRight, Tuple.Create("forestPlayground", 13)},
        {ApConnectionId.RaveEntrance, Tuple.Create("forestRaveIntersection", 5)},
        {ApConnectionId.OutsideRaveLeft, Tuple.Create("forestRaveIntersection", 13)},
        {ApConnectionId.RaveExit, Tuple.Create("forestRave", 5)},
        {ApConnectionId.PhotoGuildHutEntrance, Tuple.Create("harborBusStop", 10)},
        {ApConnectionId.StanhamnBusStopLeft, Tuple.Create("harborBusStop", 5)},
        {ApConnectionId.StanhamnBusStopRight, Tuple.Create("harborBusStop", 2)},
        {ApConnectionId.PhotoGuildHutExit, Tuple.Create("harborPhotoGuildInside", 10)},
        {ApConnectionId.PirateDrawbridgeRight, Tuple.Create("harborBridgeBeachCentrum", 5)},
        {ApConnectionId.PirateDrawbridgeLeft, Tuple.Create("harborBridgeBeachCentrum", 1)},
        {ApConnectionId.HippoBeachRight, Tuple.Create("harborBeach", 1)},
        {ApConnectionId.HippoBeachManhole, Tuple.Create("harborBeach", 9)},
        {ApConnectionId.HippoBeachLeft, Tuple.Create("harborBeach", 2)},
        {ApConnectionId.UnderwaterExit, Tuple.Create("harborUnderwater", 9)},
        {ApConnectionId.OutsideLighthouseRight, Tuple.Create("harborHonkhouse", 2)},
        {ApConnectionId.OutsideLighthouseUp, Tuple.Create("harborHonkhouse", 1)},
        {ApConnectionId.LighthouseEntrance, Tuple.Create("harborHonkhouse", 80)},
        {ApConnectionId.LighthouseExit, Tuple.Create("harborHonkHouseInside", 80)},
        {ApConnectionId.LighthouseRoofEntrance, Tuple.Create("harborHonkHouseInside", 8)},
        {ApConnectionId.LighthouseRoofExit, Tuple.Create("harborHonkHouseTop", 8)},
        {ApConnectionId.KingFishBeachExit, Tuple.Create("harborCliffs", 1)},
        {ApConnectionId.DocksLeftExit, Tuple.Create("harborDocks", 2)},
        {ApConnectionId.DocksRightExit, Tuple.Create("harborDocks", 1)},
        {ApConnectionId.FishingTowerLeft, Tuple.Create("harborFishingTower", 1)},
        {ApConnectionId.FishingTowerUp, Tuple.Create("harborFishingTower", 2)},
        {ApConnectionId.GhostDrawbridgeLeft, Tuple.Create("harborBridgeFishingHydro", 5)},
        {ApConnectionId.GhostDrawbridgeDown, Tuple.Create("harborBridgeFishingHydro", 2)},
        {ApConnectionId.HydroplantEntrance, Tuple.Create("harborHydroplant", 8)},
        {ApConnectionId.OutsideHydroplantRight, Tuple.Create("harborHydroplant", 5)},
        {ApConnectionId.HydroplantExit, Tuple.Create("harborHydroplant_Inside", 8)},
        {ApConnectionId.EscalatorUp, Tuple.Create("cityBusStop", 1)},
        {ApConnectionId.LogcityBusStopEntrance, Tuple.Create("cityHub", 1)},
        {ApConnectionId.ClockTowerLeft, Tuple.Create("cityHub", 8)},
        {ApConnectionId.ClockTowerUp, Tuple.Create("cityHub", 3)},
        {ApConnectionId.ClockTowerRight, Tuple.Create("cityHub", 4)},
        {ApConnectionId.CrossWalkRight, Tuple.Create("cityParking", 8)},
        {ApConnectionId.CrossWalkUp, Tuple.Create("cityParking", 1)},
        {ApConnectionId.OverpassDown, Tuple.Create("cityOverpass", 1)},
        {ApConnectionId.NewsHouseEntrance, Tuple.Create("cityOverpass", 15)},
        {ApConnectionId.OverpassUp, Tuple.Create("cityOverpass", 3)},
        {ApConnectionId.OverpassRight, Tuple.Create("cityOverpass", 4)},
        {ApConnectionId.NewsHouseExit, Tuple.Create("cityNewsHouseInside", 15)},
        {ApConnectionId.SkateParkDown, Tuple.Create("citySkateboard", 3)},
        {ApConnectionId.SkateParkRight, Tuple.Create("citySkateboard", 1)},
        {ApConnectionId.SkateParkTaxi, Tuple.Create("citySkateboard", 500)},
        {ApConnectionId.RatskullzAlleyExit, Tuple.Create("cityAlley", 1)},
        {ApConnectionId.FashionShowEntrance, Tuple.Create("cityBigTown", 20)},
        {ApConnectionId.OutsideFashionShowDown, Tuple.Create("cityBigTown", 3)},
        {ApConnectionId.OutsideFashionShowLeft, Tuple.Create("cityBigTown", 4)},
        {ApConnectionId.OutsideFashionShowRight, Tuple.Create("cityBigTown", 2)},
        {ApConnectionId.FashionShowBackstageEntrance, Tuple.Create("cityFashionShow", 201)},
        {ApConnectionId.FashionShowExit, Tuple.Create("cityFashionShow", 20)},
        {ApConnectionId.FashionShowBackstageExit, Tuple.Create("cityFashionShowBackstage", 201)},
        {ApConnectionId.CafeEntrance, Tuple.Create("cityCafe", 200)},
        {ApConnectionId.OutsideCafeLeft, Tuple.Create("cityCafe", 4)},
        {ApConnectionId.OutsideCafeUp, Tuple.Create("cityCafe", 5)},
        {ApConnectionId.OutsideCafeTaxi, Tuple.Create("cityCafe", 500)},
        {ApConnectionId.CafeExit, Tuple.Create("cityCafeInside", 200)},
        {ApConnectionId.GalleryEntrance, Tuple.Create("cityGallery", 6)},
        {ApConnectionId.OutsideGalleryShowDown, Tuple.Create("cityGallery", 5)},
        {ApConnectionId.OutsideGalleryShowLeft, Tuple.Create("cityGallery", 2)},
        {ApConnectionId.GalleryExit, Tuple.Create("cityGalleryInside", 6)},
        {ApConnectionId.KiirubergBusStopUp, Tuple.Create("mountainBusStop", 1)},
        {ApConnectionId.BalloonHouseEntrance, Tuple.Create("mountainTown", 23)},
        {ApConnectionId.BirthdayPartyDown, Tuple.Create("mountainTown", 1)},
        {ApConnectionId.BirthdayPartyLeft, Tuple.Create("mountainTown", 4)},
        {ApConnectionId.BirthdayPartyRight, Tuple.Create("mountainTown", 3)},
        {ApConnectionId.BirthdayPartyUp, Tuple.Create("mountainTown", 2)},
        {ApConnectionId.BalloonHouseExit, Tuple.Create("mountainTownInside", 23)},
        {ApConnectionId.OldMansHouseEntrance, Tuple.Create("mountainLakeLonely", 8)},
        {ApConnectionId.FrozenPondRight, Tuple.Create("mountainLakeLonely", 4)},
        {ApConnectionId.OldMansHouseExit, Tuple.Create("mountainOldManInside", 8)},
        {ApConnectionId.MilitaryBaseEntrance, Tuple.Create("mountainTown2", 100)},
        {ApConnectionId.MecksHouseEntrance, Tuple.Create("mountainTown2", 80)},
        {ApConnectionId.SnowmanSquareDown, Tuple.Create("mountainTown2", 2)},
        {ApConnectionId.SnowmanSquareLeft, Tuple.Create("mountainTown2", 8)},
        {ApConnectionId.SnowmanSquareUp, Tuple.Create("mountainTown2", 5)},
        {ApConnectionId.MilitaryBaseExit, Tuple.Create("mountainMilitary", 100)},
        {ApConnectionId.MecksHouseExit, Tuple.Create("mountainMeckInside", 80)},
        {ApConnectionId.WizardTowerEntrance, Tuple.Create("mountainWizard", 99)},
        {ApConnectionId.OutsideWizardTowerRight, Tuple.Create("mountainWizard", 8)},
        {ApConnectionId.WizardPortalEntrance, Tuple.Create("mountainWizardInside", 999)},
        {ApConnectionId.WizardTowerExit, Tuple.Create("mountainWizardInside", 99)},
        {ApConnectionId.WizardPortalExit, Tuple.Create("CosmoGarden", 999)},
        {ApConnectionId.CliffsDown, Tuple.Create("mountainCliff", 5)},
        {ApConnectionId.CliffsRight, Tuple.Create("mountainCliff", 2)},
        {ApConnectionId.CliffsUp, Tuple.Create("mountainCliff", 1)},
        {ApConnectionId.BlizzardBridgeLeft, Tuple.Create("mountainWindyLobby", 2)},
        {ApConnectionId.ManCaveEntrance, Tuple.Create("mountainWindyLobby", 200)},
        {ApConnectionId.BlizzardBridgeRight, Tuple.Create("mountainWindyLobby", 3)},
        {ApConnectionId.ManCaveExit, Tuple.Create("mountainManCave", 200)},
        {ApConnectionId.BlizzardMonsterExit, Tuple.Create("mountainWindyEnd", 3)},
        {ApConnectionId.ObservatoryEntrance, Tuple.Create("mountainObservatoryTop", 40)},
        {ApConnectionId.OutsideObservatoryDown, Tuple.Create("mountainObservatoryTop", 1)},
        {ApConnectionId.OutsideObservatoryRight, Tuple.Create("mountainObservatoryTop", 2)},
        {ApConnectionId.ObservatoryExit, Tuple.Create("mountainObservatory", 40)},
        {ApConnectionId.SkiLodgeEntrance, Tuple.Create("mountainSkiCabin", 9)},
        {ApConnectionId.SkiLiftBaseLeft, Tuple.Create("mountainSkiCabin", 3)},
        {ApConnectionId.SkiLodgeExit, Tuple.Create("mountainSkiCabinInside", 9)},
        {ApConnectionId.SkiMountainTopLeft, Tuple.Create("mountainSkiTop", 2)},
        {ApConnectionId.MountainTopBusStopClimb, Tuple.Create("mountainTop", 0)},
        {ApConnectionId.ToemDescend, Tuple.Create("mountainTopToem", 0)},
        {ApConnectionId.BastoHarborUp, Tuple.Create("resortBusstop", 1)},
        {ApConnectionId.LilyPadPondDown, Tuple.Create("resortCenter", 1)},
        {ApConnectionId.LilyPadPondLeft, Tuple.Create("resortCenter", 2)},
        {ApConnectionId.LilyPadPondRight, Tuple.Create("resortCenter", 3)},
        {ApConnectionId.LilyPadPondUp, Tuple.Create("resortCenter", 4)},
        {ApConnectionId.TentEntrance, Tuple.Create("resortNana", 10)},
        {ApConnectionId.CampsiteRight, Tuple.Create("resortNana", 2)},
        {ApConnectionId.TentExit, Tuple.Create("resortHomeTent", 10)},
        {ApConnectionId.CastleEntrance, Tuple.Create("resortCastle", 2)},
        {ApConnectionId.GymHouseEntrance, Tuple.Create("resortCastle", 20)},
        {ApConnectionId.OutsideCastleDown, Tuple.Create("resortCastle", 4)},
        {ApConnectionId.OutsideCastleLeft, Tuple.Create("resortCastle", 5)},
        {ApConnectionId.CastleExit, Tuple.Create("resortCastleInside", 2)},
        {ApConnectionId.GymHouseExit, Tuple.Create("resortDrinkInside", 20)},
        {ApConnectionId.BonfireLowerRight, Tuple.Create("resortDino", 5)},
        {ApConnectionId.BonfireUpperRight, Tuple.Create("resortDino", 12)},
        {ApConnectionId.CarnivalEntrance, Tuple.Create("resortDino", 7)},
        {ApConnectionId.CarnivalExit, Tuple.Create("resortCarnivalInside", 7)},
        {ApConnectionId.GhostHangoutCaveEntrance, Tuple.Create("resortGhost", 40)},
        {ApConnectionId.GhostHangoutLeft, Tuple.Create("resortGhost", 3)},
        {ApConnectionId.SecretCaveRoomEntrance, Tuple.Create("resortCaveTrail", 10)},
        {ApConnectionId.GhostHangoutCaveExit, Tuple.Create("resortCaveTrail", 40)},
        {ApConnectionId.JungleCaveExit, Tuple.Create("resortCaveTrail", 41)},
        {ApConnectionId.SecretCaveRoomExit, Tuple.Create("resortSecretCave", 10)},
        {ApConnectionId.JungleCaveEntrance, Tuple.Create("resortJungle", 41)},
        {ApConnectionId.JungleLeft, Tuple.Create("resortJungle", 12)},
    };
}
