using System;
using System.Collections.Generic;
using Quests;

namespace Archipelago.TOEM;

public enum ApLocationId
{
    QuestPhotoOfNana = 1,
    QuestHiddenGift,
    QuestExperienceToem,
    CompCow,
    CompFlies,
    CompHomeBird,
    CompTato,
    ItemClogs,
    ItemAwardMask,
    TapePhotoOfHome,
    CheevoBeginning,
    CheevoHomeSweetHome,
    QuestSusForest,
    QuestMonsters,
    QuestSocks,
    QuestScouts,
    QuestHideAndSeek,
    QuestLogJam,
    QuestChallenge1,
    QuestChallenge2,
    QuestPaparazzi,
    QuestCaptureHotel,
    QuestHotelChef,
    QuestStallion,
    QuestGhostHelper,
    QuestCupChamp,
    QuestFlower,
    CompAnt,
    CompBeehive,
    CompButterfly,
    CompOskar,
    CompSero,
    CompForestBird,
    CompLadybug,
    CompTom,
    CompNestworm,
    CompPetRock,
    CompSnail,
    CompSquirrel,
    CompStagBeetle,
    CompTatoBug,
    CompTatoFly,
    ItemFinger,
    ItemTripod,
    ItemCowboyHat,
    ItemWetSocks,
    ItemFjallbjornHat,
    ItemGhostGlasses,
    ItemSoakedSock,
    ItemMonsterMask,
    TapeSummerBreeze,
    TapeSquirrelHotel,
    TapePineNeedles,
    TapeSquirrelPhoto,
    CheevoCalmForest,
    CheevoMajesticHotel,
    CheevoSlowAndSteady,
    CheevoNatureShowstopper,
    CheevoStrongAsAnOak,
    CheevoCalmedDown,
    CheevoJustASock,
    CheevoYouFoundUs,
    QuestKingFish,
    QuestGoodSpot,
    QuestSusHarbor,
    QuestPaperHats,
    QuestChallenge3,
    QuestChallenge4,
    QuestFramesFilters,
    QuestTakeABath,
    QuestLostDog,
    QuestPower,
    QuestChaos,
    QuestFlame,
    QuestSandwich,
    QuestGarbage,
    QuestWhistling,
    QuestMelody,
    CompBubbleFly,
    CompFia,
    CompFras,
    CompWillemijn,
    CompCrab,
    CompDragonfly,
    CompHappyCarp,
    CompJellyfish,
    CompKingFish,
    CompSeagull,
    CompSeahorse,
    CompSundaySwan,
    CompTatoScuba,
    CompTatoSwim,
    CompToad,
    ItemFramesFilters,
    ItemFishingHat,
    ItemHonkAttachment,
    ItemUmbrella,
    ItemOldKey,
    ItemHardHat,
    ItemDivingHelmet,
    ItemRubberBoots,
    ItemSandwich,
    ItemPirateHat,
    ItemPaperHat,
    ItemFlag,
    TapeFishermansWhistle,
    TapeSmilingHuntsman,
    TapeNaut,
    TapePlaceInSun,
    TapeFishermansTune,
    CheevoSetSail,
    CheevoVoyageUnderwater,
    CheevoEmployeeOfTheMonth,
    CheevoCalmAsSea,
    CheevoSeaworthy,
    CheevoFlightReady,
    CheevoSparklingJump,
    CheevoGoodBoy,
    QuestSusCity,
    QuestRatskullz,
    QuestPunkRocker,
    QuestChallenge5,
    QuestChallenge6,
    QuestNews,
    QuestSewer,
    QuestHotbean,
    QuestHangInThere,
    QuestScaryCity,
    QuestDate,
    QuestArt,
    QuestInfluencer,
    QuestFashion,
    QuestCleaning,
    QuestGranny,
    QuestMice,
    QuestCrow,
    CompBusinessPigeon,
    CompPortillo,
    CompMouse,
    CompPigeon,
    CompPunkParrot,
    CompTatoSkateboard,
    CompTatoTourist,
    CompTurtle,
    ItemHotbeanHat,
    ItemReporterHat,
    ItemSneakers,
    ItemCinnamonBun,
    ItemFrisbee,
    TapeRatskullzTheme,
    TapeBigCity,
    TapeHustleBustle,
    TapeHopSkipStep,
    TapeOnTheHour,
    CheevoBigCity,
    CheevoClocktower,
    CheevoProfessional,
    CheevoBusiness,
    CheevoFollowers,
    CheevoNewJob,
    QuestYetiCute,
    QuestIceWizard,
    QuestMilitarySus,
    QuestAstronaut,
    QuestChallenge7,
    QuestChallenge8,
    QuestAsteroid,
    QuestGoatChoir,
    QuestSnowball,
    QuestBirthday,
    QuestPaintings,
    QuestBecomeYeti,
    QuestSnowman,
    CompMikee,
    CompNariko,
    CompCosmoDeer,
    CompTeddy,
    CompFluff,
    CompHedgehog,
    CompMeteopal,
    CompGoat,
    CompOwl,
    CompSnowBird,
    CompTatoAlien,
    CompTatoSki,
    ItemClimbingBoots,
    ItemPufferHat,
    ItemScarf,
    ItemSkiGoggles,
    ItemSpaceHelmet,
    TapeLifeThroughLens,
    TapePettingDeer,
    TapeStoriesOfSnow,
    TapeTallShy,
    CheevoSnowyPeaks,
    CheevoGearedUp,
    CheevoHurdle,
    CheevoFighter,
    CheevoYouth,
    CheevoStory,
    CheevoClose,
    CheevoToem,
    CheevoCuties,
    CheevoCollectEmAll,
    CheevoGoingLong,
    CheevoCosplayer,
    CheevoCompletionist,
    FirstBasto,
    QuestBalloons = FirstBasto,
    QuestArthur,
    QuestBadHairDay,
    QuestTakeANap,
    QuestSpookyStories,
    QuestPortraits,
    QuestCinema,
    QuestNightLights,
    QuestJetSki,
    QuestFruits,
    QuestBrainFreeze,
    QuestSweetTooth,
    QuestInYourFace,
    QuestBrokenDreams,
    QuestDrySeason,
    QuestMuscles,
    QuestSandCastle,
    QuestCarnival,
    QuestBats,
    QuestBitling,
    CompBat,
    CompSnake,
    CompBeakBird,
    CompBitlingFrog,
    CompBitlingMouse,
    CompBitlingSnail,
    CompBitlingTato,
    CompCocoCrab,
    CompDayLizard,
    CompDrillMole,
    CompEggert,
    CompFireFly,
    CompGlowWorm,
    CompItsyBitsy,
    CompMudFrog,
    CompNightLizard,
    CompSnoutBug,
    CompTatoCoco,
    CompTatoKing,
    CompWaterStrider,
    ItemBastoTicket,
    ItemWatergun,
    ItemSunHat,
    ItemMelonear,
    ItemBanakin,
    ItemOranganas,
    ItemBeanut,
    ItemPickaxe,
    ItemSunCap,
    ItemFlipFlops,
    ItemIceCreamBanakin,
    ItemIceCreamMelonear,
    ItemIceCreamBeanut,
    ItemIceCreamOranganas,
    ItemRoyalCape,
    ItemMinigameTicket,
    ItemLei,
    ItemVacationShirt,
    ItemRoyalCane,
    ItemEmptyBottle,
    ItemVikingHelmet,
    ItemFootCast,
    ItemBeret,
    ItemRoyalCrown,
    TapeNightJam,
    TapeWarmDaysNight,
    TapeOneByOne,
    TapeHammockDays,
    TapeSailorsTune,
    TapeSongOfTheSea,
    CheevoTropicalParadise,
    CheevoMaximumVacation,
    CheevoKingsShirt,
    CheevoMoonlitBeauty,
    CheevoSelfPortrait,
    CheevoWazzuuppp,
    CheevoProGamer,
    CheevoSplishSplash,
    CheevoRoyalCastle,
    CheevoSomeMore,
    CheevoVikingsHoliday,
}

public enum ApItemId
{
    StampHomelanda = 1,
    StampOaklaville,
    StampStanhamn,
    StampLogcity,
    StampKiiruberg,
    StampBasto,
    ProgressiveStamp,
    LastStamp = ProgressiveStamp,
    PhotoCow,
    PhotoFlies,
    PhotoHomeBird,
    PhotoTato,
    PhotoAnt,
    PhotoBeehive,
    PhotoButterfly,
    PhotoOskar,
    PhotoSero,
    PhotoForestBird,
    PhotoLadybug,
    PhotoTom,
    PhotoNestworm,
    PhotoPetRock,
    PhotoSnail,
    PhotoSquirrel,
    PhotoStagBeetle,
    PhotoTatoBug,
    PhotoTatoFly,
    PhotoBubbleFly,
    PhotoFia,
    PhotoFras,
    PhotoWillemijn,
    PhotoCrab,
    PhotoDragonfly,
    PhotoHappyCarp,
    PhotoJellyfish,
    PhotoKingFish,
    PhotoSeagull,
    PhotoSeahorse,
    PhotoSundaySwan,
    PhotoTatoScuba,
    PhotoTatoSwim,
    PhotoToad,
    PhotoBusinessPigeon,
    PhotoPortillo,
    PhotoMouse,
    PhotoPigeon,
    PhotoPunkParrot,
    PhotoTatoSkateboard,
    PhotoTatoTourist,
    PhotoTurtle,
    PhotoMikee,
    PhotoNariko,
    PhotoCosmoDeer,
    PhotoTeddy,
    PhotoFluff,
    PhotoHedgehog,
    PhotoMeteopal,
    PhotoGoat,
    PhotoOwl,
    PhotoSnowBird,
    PhotoTatoAlien,
    PhotoTatoSki,
    PhotoBat,
    PhotoSnake,
    PhotoBeakBird,
    PhotoBitlingFrog,
    PhotoBitlingMouse,
    PhotoBitlingSnail,
    PhotoBitlingTato,
    PhotoCocoCrab,
    PhotoDayLizard,
    PhotoDrillMole,
    PhotoEggert,
    PhotoFireFly,
    PhotoGlowWorm,
    PhotoItsyBitsy,
    PhotoMudFrog,
    PhotoNightLizard,
    PhotoSnoutBug,
    PhotoTatoCoco,
    PhotoTatoKing,
    PhotoWaterStrider,
    LastPhoto = PhotoWaterStrider,
    Clogs,
    AwardMask,
    Finger,
    Tripod,
    CowboyHat,
    WetSocks,
    FjallbjornHat,
    GhostGlasses,
    SoakedSock,
    MonsterMask,
    FramesFilters,
    FishingHat,
    HonkAttachment,
    Umbrella,
    OldKey,
    HardHat,
    DivingHelmet,
    RubberBoots,
    Sandwich,
    PirateHat,
    PaperHat,
    Flag,
    HotbeanHat,
    ReporterHat,
    Sneakers,
    CinnamonBun,
    Frisbee,
    ClimbingBoots,
    PufferHat,
    Scarf,
    SkiGoggles,
    SpaceHelmet,
    BastoTicket,
    Watergun,
    SunHat,
    Melonear,
    Banakin,
    Oranganas,
    Beanut,
    Pickaxe,
    SunCap,
    FlipFlops,
    IceCream,
    RoyalCape,
    MinigameTicket,
    Lei,
    VacationShirt,
    RoyalCane,
    EmptyBottle,
    VikingHelmet,
    FootCast,
    Beret,
    RoyalCrown,
    LastItem = RoyalCrown,
    PhotoOfHomeTape,
    SummerBreezeTape,
    SquirrelHotelTape,
    PineNeedlesTape,
    SquirrelPhotoTape,
    FishermansWhistleTape,
    SmilingHuntsmanTape,
    NautTape,
    PlaceInSunTape,
    FishermansTuneTape,
    RatskullzThemeTape,
    BigCityTape,
    HustleBustleTape,
    HopSkipStepTape,
    OnTheHourTape,
    LifeThroughLensTape,
    PettingDeerTape,
    StoriesOfSnowTape,
    TallShyTape,
    NightJamTape,
    WarmDaysNightTape,
    OneByOneTape,
    HammockDaysTape,
    SailorsTuneTape,
    SongOfTheSeaTape,
    LastCassette = SongOfTheSeaTape,
}

public static class Data
{
    public static readonly Dictionary<string, ApLocationId> QuestToApLocationId = new() {
        {"Photo of Nana", ApLocationId.QuestPhotoOfNana},
        {"A Hidden Gift", ApLocationId.QuestHiddenGift},
        {"Experience TOEM", ApLocationId.QuestExperienceToem},
        {"Submarine - Forest", ApLocationId.QuestSusForest},
        {"Monster Collector", ApLocationId.QuestMonsters},
        {"Sockman", ApLocationId.QuestSocks},
        {"Become a scout - Scout Leader", ApLocationId.QuestScouts},
        {"Scout Hide And Seek", ApLocationId.QuestHideAndSeek},
        {"Pine Critters", ApLocationId.QuestLogJam},
        {"Photo Challenger Boy Forest", ApLocationId.QuestChallenge1},
        {"Photo Challenger Forest Girl", ApLocationId.QuestChallenge2},
        {"Paparazzi", ApLocationId.QuestPaparazzi},
        {"Hotel Owner - Capture Hotel's Beauty", ApLocationId.QuestCaptureHotel},
        {"Hotel Chef", ApLocationId.QuestHotelChef},
        {"Ghost Horse Stallion", ApLocationId.QuestStallion},
        {"Ghost Helper", ApLocationId.QuestGhostHelper},
        {"Ghost Cup", ApLocationId.QuestCupChamp},
        {"Become a Flower", ApLocationId.QuestFlower},
        {"The king of fishes", ApLocationId.QuestKingFish},
        {"Sunbather", ApLocationId.QuestGoodSpot},
        {"Submarine - Harbor", ApLocationId.QuestSusHarbor},
        {"Pirate Queen", ApLocationId.QuestPaperHats},
        {"Photo Challenger Boy Harbor", ApLocationId.QuestChallenge3},
        {"Photo Challenger Girl Harbor", ApLocationId.QuestChallenge4},
        {"Photo Challenger Frame", ApLocationId.QuestFramesFilters},
        {"Make someone take a bath", ApLocationId.QuestTakeABath},
        {"Lost Dog", ApLocationId.QuestLostDog},
        {"Hydroplant - Power shortage!", ApLocationId.QuestPower},
        {"Honk Master", ApLocationId.QuestChaos},
        {"Ghost Splat", ApLocationId.QuestFlame},
        {"Ghost Grumpy", ApLocationId.QuestSandwich},
        {"Fishing Tower", ApLocationId.QuestGarbage},
        {"Barry Whistle", ApLocationId.QuestWhistling},
        {"A layered melody", ApLocationId.QuestMelody},
        {"Submarine - City", ApLocationId.QuestSusCity},
        {"Ratskullz", ApLocationId.QuestRatskullz},
        {"Punk Rocker", ApLocationId.QuestPunkRocker},
        {"Photo Challenger Boy City", ApLocationId.QuestChallenge5},
        {"Photo Challenger Girl City", ApLocationId.QuestChallenge6},
        {"Office Director - Press-ing News", ApLocationId.QuestNews},
        {"Manhole", ApLocationId.QuestSewer},
        {"Hotbean Cart", ApLocationId.QuestHotbean},
        {"Hang in there buddy", ApLocationId.QuestHangInThere},
        {"Ghost Nature", ApLocationId.QuestScaryCity},
        {"Ghost Date", ApLocationId.QuestDate},
        {"Gallery Owner - Art Exhibition", ApLocationId.QuestArt},
        {"Food Influencer", ApLocationId.QuestInfluencer},
        {"Fashion Show - Design Problem", ApLocationId.QuestFashion},
        {"Cleaning away the stress", ApLocationId.QuestCleaning},
        {"Always Tumbled Granny", ApLocationId.QuestGranny},
        {"A Mouse Bakery", ApLocationId.QuestMice},
        {"A Thieving Crow", ApLocationId.QuestCrow},
        {"Yeti Cuteness", ApLocationId.QuestYetiCute},
        {"Wizard Inventor", ApLocationId.QuestIceWizard},
        {"Suspicious Activity - Military Base", ApLocationId.QuestMilitarySus},
        {"Play astronaut", ApLocationId.QuestAstronaut},
        {"Photo Challenger Boy Mountain", ApLocationId.QuestChallenge7},
        {"Photo Challenger Girl Mountain", ApLocationId.QuestChallenge8},
        {"Observatory Scientist", ApLocationId.QuestAsteroid},
        {"Goat Choir", ApLocationId.QuestGoatChoir},
        {"Snowball Memories", ApLocationId.QuestSnowball},
        {"Birthday Balloon In Distress", ApLocationId.QuestBirthday},
        {"Mountain Explorer", ApLocationId.QuestPaintings},
        {"Become a Yeti", ApLocationId.QuestBecomeYeti},
        {"Assemble a Snowman", ApLocationId.QuestSnowman},
        {"Bastu Balloons", ApLocationId.QuestBalloons},
        {"Treasure Hunter", ApLocationId.QuestArthur},
        {"Tangled Hair", ApLocationId.QuestBadHairDay},
        {"Take a nap", ApLocationId.QuestTakeANap},
        {"Spooky Story", ApLocationId.QuestSpookyStories},
        {"Painter - Closeup", ApLocationId.QuestPortraits},
        {"Nighttime Cinema", ApLocationId.QuestCinema},
        {"Night Lights", ApLocationId.QuestNightLights},
        {"Jetski Tricks", ApLocationId.QuestJetSki},
        {"Ice Cream Vendor", ApLocationId.QuestFruits},
        {"Ice Cream - Zombert", ApLocationId.QuestBrainFreeze},
        {"Ice Cream - Vampire", ApLocationId.QuestSweetTooth},
        {"Ice Cream - Prince", ApLocationId.QuestInYourFace},
        {"Ice Cream - Monkey", ApLocationId.QuestBrokenDreams},
        {"Dry Season", ApLocationId.QuestDrySeason},
        {"Dehydrated Muscles", ApLocationId.QuestMuscles},
        {"Castle Competition", ApLocationId.QuestSandCastle},
        {"Carnival Game", ApLocationId.QuestCarnival},
        {"Book of Bats", ApLocationId.QuestBats},
        {"Bitling Collector", ApLocationId.QuestBitling},
    };

    public static readonly Dictionary<string, ApLocationId> CreatureToApLocationId = new() {
        {"Cow", ApLocationId.CompCow},
        {"Flies", ApLocationId.CompFlies},
        {"Home Bird", ApLocationId.CompHomeBird},
        {"Tato", ApLocationId.CompTato},
        {"Ant", ApLocationId.CompAnt},
        {"Beehive", ApLocationId.CompBeehive},
        {"Butterfly", ApLocationId.CompButterfly},
        {"Oskar", ApLocationId.CompOskar},
        {"Sero", ApLocationId.CompSero},
        {"Forest Bird", ApLocationId.CompForestBird},
        {"Ladybug", ApLocationId.CompLadybug},
        {"Tom", ApLocationId.CompTom},
        {"Nestworm", ApLocationId.CompNestworm},
        {"Pet Rock", ApLocationId.CompPetRock},
        {"Snail", ApLocationId.CompSnail},
        {"Squirrel", ApLocationId.CompSquirrel},
        {"Stag Beetle", ApLocationId.CompStagBeetle},
        {"Tato Bug", ApLocationId.CompTatoBug},
        {"Tato Fly", ApLocationId.CompTatoFly},
        {"Bubble Fly", ApLocationId.CompBubbleFly},
        {"Fia", ApLocationId.CompFia},
        {"Fräs", ApLocationId.CompFras},
        {"Willemijn", ApLocationId.CompWillemijn},
        {"Crab", ApLocationId.CompCrab},
        {"Dragonfly", ApLocationId.CompDragonfly},
        {"Happy Carp", ApLocationId.CompHappyCarp},
        {"Jellyfish", ApLocationId.CompJellyfish},
        {"King Fish", ApLocationId.CompKingFish},
        {"Seagull", ApLocationId.CompSeagull},
        {"Seahorse", ApLocationId.CompSeahorse},
        {"Sunday Swan", ApLocationId.CompSundaySwan},
        {"Tato Scuba", ApLocationId.CompTatoScuba},
        {"Tato Swim", ApLocationId.CompTatoSwim},
        {"Toad", ApLocationId.CompToad},
        {"Business Pigeon", ApLocationId.CompBusinessPigeon},
        {"Portillo", ApLocationId.CompPortillo},
        {"Mouse", ApLocationId.CompMouse},
        {"Pigeon", ApLocationId.CompPigeon},
        {"Punky Parrot", ApLocationId.CompPunkParrot},
        {"Tato Skateboard", ApLocationId.CompTatoSkateboard},
        {"Tato Tourist", ApLocationId.CompTatoTourist},
        {"Turtle", ApLocationId.CompTurtle},
        {"Mikée", ApLocationId.CompMikee},
        {"Nariko", ApLocationId.CompNariko},
        {"Cosmo Deer", ApLocationId.CompCosmoDeer},
        {"Teddy", ApLocationId.CompTeddy},
        {"Fluff Ball", ApLocationId.CompFluff},
        {"Hedgehog", ApLocationId.CompHedgehog},
        {"Meteopal", ApLocationId.CompMeteopal},
        {"Mountain Goat", ApLocationId.CompGoat},
        {"Owl", ApLocationId.CompOwl},
        {"Snow Bird", ApLocationId.CompSnowBird},
        {"Tato Alien", ApLocationId.CompTatoAlien},
        {"Tato Ski", ApLocationId.CompTatoSki},
        {"Bat", ApLocationId.CompBat},
        {"Beach Snake", ApLocationId.CompSnake},
        {"Beak Bird", ApLocationId.CompBeakBird},
        {"Bitling Frog", ApLocationId.CompBitlingFrog},
        {"Bitling Mouse", ApLocationId.CompBitlingMouse},
        {"Bitling Snail", ApLocationId.CompBitlingSnail},
        {"Bitling Tato", ApLocationId.CompBitlingTato},
        {"Coco Crab", ApLocationId.CompCocoCrab},
        {"Day Lizard", ApLocationId.CompDayLizard},
        {"Drill Mole", ApLocationId.CompDrillMole},
        {"Eggert", ApLocationId.CompEggert},
        {"Fire Fly", ApLocationId.CompFireFly},
        {"Glow Worm", ApLocationId.CompGlowWorm},
        {"Itsy Bitsy", ApLocationId.CompItsyBitsy},
        {"Mud Frog", ApLocationId.CompMudFrog},
        {"Night Lizard", ApLocationId.CompNightLizard},
        {"Snout Bug", ApLocationId.CompSnoutBug},
        {"Tato Coco", ApLocationId.CompTatoCoco},
        {"Tato King", ApLocationId.CompTatoKing},
        {"Water Strider", ApLocationId.CompWaterStrider},
    };

    public static readonly Dictionary<string, ApLocationId> ItemToApLocationId = new() {
        {"Clogs", ApLocationId.ItemClogs},
        {"AwardMask", ApLocationId.ItemAwardMask},
        {"FoamFinger", ApLocationId.ItemFinger},
        {"Tripod", ApLocationId.ItemTripod},
        {"CowboyHat", ApLocationId.ItemCowboyHat},
        {"Pair of Socks", ApLocationId.ItemWetSocks},
        {"ScoutHat", ApLocationId.ItemFjallbjornHat},
        {"Sunglasses", ApLocationId.ItemGhostGlasses},
        {"Soaked Sock", ApLocationId.ItemSoakedSock},
        {"MonsterMask", ApLocationId.ItemMonsterMask},
        {"Camera Frames", ApLocationId.ItemFramesFilters},
        {"FishingHat", ApLocationId.ItemFishingHat},
        {"Honk", ApLocationId.ItemHonkAttachment},
        {"Umbrella", ApLocationId.ItemUmbrella},
        {"Pirate Key", ApLocationId.ItemOldKey},
        {"Hardhat", ApLocationId.ItemHardHat},
        {"DiverHelmet", ApLocationId.ItemDivingHelmet},
        {"Rubber Boots", ApLocationId.ItemRubberBoots},
        {"SupremeSandwich", ApLocationId.ItemSandwich},
        {"PirateHat", ApLocationId.ItemPirateHat},
        {"PaperHat", ApLocationId.ItemPaperHat},
        {"PhotoFlag", ApLocationId.ItemFlag},
        {"Hotbean Hat", ApLocationId.ItemHotbeanHat},
        {"ReporterHat", ApLocationId.ItemReporterHat},
        {"Sneakers", ApLocationId.ItemSneakers},
        {"Cinnamonbun", ApLocationId.ItemCinnamonBun},
        {"Frisbee", ApLocationId.ItemFrisbee},
        {"Snow Boots", ApLocationId.ItemClimbingBoots},
        {"Puff Hat", ApLocationId.ItemPufferHat},
        {"Scarf", ApLocationId.ItemScarf},
        {"SkiGoggles", ApLocationId.ItemSkiGoggles},
        {"SpaceHelmet", ApLocationId.ItemSpaceHelmet},
        {"Bastu Ticket", ApLocationId.ItemBastoTicket},
        {"Water Balloon", ApLocationId.ItemWatergun},
        {"Sunhat", ApLocationId.ItemSunHat},
        {"Fruit Pear", ApLocationId.ItemMelonear},
        {"Fruit Banana", ApLocationId.ItemBanakin},
        {"Fruit Orange", ApLocationId.ItemOranganas},
        {"Fruit Bean", ApLocationId.ItemBeanut},
        {"Pickaxe", ApLocationId.ItemPickaxe},
        {"Suncap", ApLocationId.ItemSunCap},
        {"Flipflops", ApLocationId.ItemFlipFlops},
        {"Ice Cream", ApLocationId.ItemIceCreamBanakin},
        {"Royal Cape", ApLocationId.ItemRoyalCape},
        {"MiniGame Ticket", ApLocationId.ItemMinigameTicket},
        {"Lei", ApLocationId.ItemLei},
        {"Vacation Shirt", ApLocationId.ItemVacationShirt},
        {"Royal Cane", ApLocationId.ItemRoyalCane},
        {"Water Bottle Empty", ApLocationId.ItemEmptyBottle},
        {"Viking Helmet", ApLocationId.ItemVikingHelmet},
        {"Foot Cast", ApLocationId.ItemFootCast},
        {"Beret", ApLocationId.ItemBeret},
        {"Crown", ApLocationId.ItemRoyalCrown},
    };
    
    public static readonly Dictionary<string, ApLocationId> CassetteToApLocationId = new() {
        //{"Jamal Green - Everybody That You Meet", ApLocationId.TapeEverybody}, // Not obtainable?
        { "Jamal Green - Photo of Home ", ApLocationId.TapePhotoOfHome},
        {"Jamal Green - Summer Breeze", ApLocationId.TapeSummerBreeze},
        {"Jamal Green - The Grand Squirrel Hotel", ApLocationId.TapeSquirrelHotel},
        {"Launchable Socks - Pine Needles", ApLocationId.TapePineNeedles},
        {"Launchable Socks - Squirrel Photography", ApLocationId.TapeSquirrelPhoto},
        {"Fisherman's Whistle", ApLocationId.TapeFishermansWhistle},
        {"JG+LS - The Smiling Huntsman", ApLocationId.TapeSmilingHuntsman},
        {"Jamal Green - NAUT", ApLocationId.TapeNaut},
        {"Launchable Socks - A Place In The Sun", ApLocationId.TapePlaceInSun},
        {"Launchable Socks - Fisherman's Tune", ApLocationId.TapeFishermansTune},
        {"Anes Sabanovic - Ratskullz Theme", ApLocationId.TapeRatskullzTheme},
        {"JG+LS - The Big City", ApLocationId.TapeBigCity},
        {"Jamal Green - Hustle Bustle Shuffle", ApLocationId.TapeHustleBustle},
        {"Launchable Socks - Hop Skip Step", ApLocationId.TapeHopSkipStep},
        {"Launchable Socks - On The Hour", ApLocationId.TapeOnTheHour},
        {"Jamal Green - Life Through a Lens", ApLocationId.TapeLifeThroughLens},
        {"Jamal Green - The Petting of a Sacred Deer", ApLocationId.TapePettingDeer},
        //{"Launchable Socks - G.O.A.T Choir", ApLocationId.TapeGoatChoir}, // Not obtainable?
        {"Launchable Socks - Stories Of Snow", ApLocationId.TapeStoriesOfSnow},
        //{"Launchable Socks - TOEM", ApLocationId.TapeToem}, // Not obtainable?
        {"Launchable Socks - Tall & Shy", ApLocationId.TapeTallShy},
        {"JG+LS - Night Jam", ApLocationId.TapeNightJam},
        {"Jamal Green - A Warm Days Night", ApLocationId.TapeWarmDaysNight},
        {"Jamal Green - One By One", ApLocationId.TapeOneByOne},
        {"Launchable Socks - Hammock Days", ApLocationId.TapeHammockDays},
        {"Launchable Socks - Sailor's Tune", ApLocationId.TapeSailorsTune},
        {"Launchable Socks - Song Of The Sea", ApLocationId.TapeSongOfTheSea},
    };

    public static readonly Dictionary<string, ApLocationId> CheevoToApLocationId = new() {
        {"Start Your Adventure", ApLocationId.CheevoBeginning},
        {"Sight Photo Home House", ApLocationId.CheevoHomeSweetHome},
        {"Visit Forest", ApLocationId.CheevoCalmForest},
        {"Sight Photo Forest OakHotel", ApLocationId.CheevoMajesticHotel},
        {"Endore snail race", ApLocationId.CheevoSlowAndSteady},
        {"Photo Challenges Forest", ApLocationId.CheevoNatureShowstopper},
        {"Quest Region Forest", ApLocationId.CheevoStrongAsAnOak},
        {"Close Up Sune The Skeleton", ApLocationId.CheevoCalmedDown},
        {"Close Up Sockman", ApLocationId.CheevoJustASock},
        {"Hotel Easter Egg", ApLocationId.CheevoYouFoundUs},
        {"Visit Harbor", ApLocationId.CheevoSetSail},
        {"Sight Photo Harbor Shipwerck", ApLocationId.CheevoVoyageUnderwater},
        {"Employee Of The Month Award", ApLocationId.CheevoEmployeeOfTheMonth},
        {"Photo Challenges Harbor", ApLocationId.CheevoCalmAsSea},
        {"Quest Region Harbor", ApLocationId.CheevoSeaworthy},
        {"Close Up Seagull", ApLocationId.CheevoFlightReady},
        {"Close Up Dancer", ApLocationId.CheevoSparklingJump},
        {"Pet a pet", ApLocationId.CheevoGoodBoy},
        {"Visit City", ApLocationId.CheevoBigCity},
        {"Sight Photo City Grand Clock Tower", ApLocationId.CheevoClocktower},
        {"Photo Challenges City", ApLocationId.CheevoProfessional},
        {"Quest Region City", ApLocationId.CheevoBusiness},
        {"Close Up Food Influencer", ApLocationId.CheevoFollowers},
        {"Close Up Stressed Human", ApLocationId.CheevoNewJob},
        {"Visit Mountain", ApLocationId.CheevoSnowyPeaks},
        {"Equip Full Snowsuit", ApLocationId.CheevoGearedUp},
        {"Photo Challenges Mountain", ApLocationId.CheevoHurdle},
        {"Quest Region Mountain", ApLocationId.CheevoFighter},
        {"Close Up Old Man", ApLocationId.CheevoYouth},
        {"Close Up Mountain Explorer", ApLocationId.CheevoStory},
        {"Visit Mountain Top", ApLocationId.CheevoClose},
        {"Sight Photo Mountain TOEM", ApLocationId.CheevoToem},
        {"Photograph the teams pets", ApLocationId.CheevoCuties},
        {"Base Game Compendium", ApLocationId.CheevoCollectEmAll},
        {"Walking with clogs", ApLocationId.CheevoGoingLong},
        {"Equip All Items Once", ApLocationId.CheevoCosplayer},
        {"Complete All Quests", ApLocationId.CheevoCompletionist},
        {"Visit Resort", ApLocationId.CheevoTropicalParadise},
        {"Vacation Mode", ApLocationId.CheevoMaximumVacation},
        {"Close Up King", ApLocationId.CheevoKingsShirt},
        {"Close Up Naked", ApLocationId.CheevoMoonlitBeauty},
        {"Close Up Player", ApLocationId.CheevoSelfPortrait},
        {"Cool Moon", ApLocationId.CheevoWazzuuppp},
        {"Play Everything At The Carnival", ApLocationId.CheevoProGamer},
        {"Take a splash", ApLocationId.CheevoSplishSplash},
        {"Sight Photo Resort", ApLocationId.CheevoRoyalCastle},
        {"Resort Compendium", ApLocationId.CheevoSomeMore},
        {"Quest Region Resort", ApLocationId.CheevoVikingsHoliday},
    };

    public static readonly Dictionary<ApLocationId, ApItemId> ApLocationIdToApItemId = new() {
        {ApLocationId.ItemClogs, ApItemId.Clogs},
        {ApLocationId.ItemAwardMask, ApItemId.AwardMask},
        {ApLocationId.ItemFinger, ApItemId.Finger},
        {ApLocationId.ItemTripod, ApItemId.Tripod},
        {ApLocationId.ItemCowboyHat, ApItemId.CowboyHat},
        {ApLocationId.ItemWetSocks, ApItemId.WetSocks},
        {ApLocationId.ItemFjallbjornHat, ApItemId.FjallbjornHat},
        {ApLocationId.ItemGhostGlasses, ApItemId.GhostGlasses},
        {ApLocationId.ItemSoakedSock, ApItemId.SoakedSock},
        {ApLocationId.ItemMonsterMask, ApItemId.MonsterMask},
        {ApLocationId.ItemFramesFilters, ApItemId.FramesFilters},
        {ApLocationId.ItemFishingHat, ApItemId.FishingHat},
        {ApLocationId.ItemHonkAttachment, ApItemId.HonkAttachment},
        {ApLocationId.ItemUmbrella, ApItemId.Umbrella},
        {ApLocationId.ItemOldKey, ApItemId.OldKey},
        {ApLocationId.ItemHardHat, ApItemId.HardHat},
        {ApLocationId.ItemDivingHelmet, ApItemId.DivingHelmet},
        {ApLocationId.ItemRubberBoots, ApItemId.RubberBoots},
        {ApLocationId.ItemSandwich, ApItemId.Sandwich},
        {ApLocationId.ItemPirateHat, ApItemId.PirateHat},
        {ApLocationId.ItemPaperHat, ApItemId.PaperHat},
        {ApLocationId.ItemFlag, ApItemId.Flag},
        {ApLocationId.ItemHotbeanHat, ApItemId.HotbeanHat},
        {ApLocationId.ItemReporterHat, ApItemId.ReporterHat},
        {ApLocationId.ItemSneakers, ApItemId.Sneakers},
        {ApLocationId.ItemCinnamonBun, ApItemId.CinnamonBun},
        {ApLocationId.ItemFrisbee, ApItemId.Frisbee},
        {ApLocationId.ItemClimbingBoots, ApItemId.ClimbingBoots},
        {ApLocationId.ItemPufferHat, ApItemId.PufferHat},
        {ApLocationId.ItemScarf, ApItemId.Scarf},
        {ApLocationId.ItemSkiGoggles, ApItemId.SkiGoggles},
        {ApLocationId.ItemSpaceHelmet, ApItemId.SpaceHelmet},
        {ApLocationId.ItemBastoTicket, ApItemId.BastoTicket},
        {ApLocationId.ItemWatergun, ApItemId.Watergun},
        {ApLocationId.ItemSunHat, ApItemId.SunHat},
        {ApLocationId.ItemMelonear, ApItemId.Melonear},
        {ApLocationId.ItemBanakin, ApItemId.Banakin},
        {ApLocationId.ItemOranganas, ApItemId.Oranganas},
        {ApLocationId.ItemBeanut, ApItemId.Beanut},
        {ApLocationId.ItemPickaxe, ApItemId.Pickaxe},
        {ApLocationId.ItemSunCap, ApItemId.SunCap},
        {ApLocationId.ItemFlipFlops, ApItemId.FlipFlops},
        {ApLocationId.ItemIceCreamBanakin, ApItemId.IceCream},
        {ApLocationId.ItemIceCreamMelonear, ApItemId.IceCream},
        {ApLocationId.ItemIceCreamBeanut, ApItemId.IceCream},
        {ApLocationId.ItemIceCreamOranganas, ApItemId.IceCream},
        {ApLocationId.ItemRoyalCape, ApItemId.RoyalCape},
        {ApLocationId.ItemMinigameTicket, ApItemId.MinigameTicket},
        {ApLocationId.ItemLei, ApItemId.Lei},
        {ApLocationId.ItemVacationShirt, ApItemId.VacationShirt},
        {ApLocationId.ItemRoyalCane, ApItemId.RoyalCane},
        {ApLocationId.ItemEmptyBottle, ApItemId.EmptyBottle},
        {ApLocationId.ItemVikingHelmet, ApItemId.VikingHelmet},
        {ApLocationId.ItemFootCast, ApItemId.FootCast},
        {ApLocationId.ItemBeret, ApItemId.Beret},
        {ApLocationId.ItemRoyalCrown, ApItemId.RoyalCrown},
        // Cassettes
        {ApLocationId.TapePhotoOfHome, ApItemId.PhotoOfHomeTape},
        {ApLocationId.TapeSummerBreeze, ApItemId.SummerBreezeTape},
        {ApLocationId.TapeSquirrelHotel, ApItemId.SquirrelHotelTape},
        {ApLocationId.TapePineNeedles, ApItemId.PineNeedlesTape},
        {ApLocationId.TapeSquirrelPhoto, ApItemId.SquirrelPhotoTape},
        {ApLocationId.TapeFishermansWhistle, ApItemId.FishermansWhistleTape},
        {ApLocationId.TapeSmilingHuntsman, ApItemId.SmilingHuntsmanTape},
        {ApLocationId.TapeNaut, ApItemId.NautTape},
        {ApLocationId.TapePlaceInSun, ApItemId.PlaceInSunTape},
        {ApLocationId.TapeFishermansTune, ApItemId.FishermansTuneTape},
        {ApLocationId.TapeRatskullzTheme, ApItemId.RatskullzThemeTape},
        {ApLocationId.TapeBigCity, ApItemId.BigCityTape},
        {ApLocationId.TapeHustleBustle, ApItemId.HustleBustleTape},
        {ApLocationId.TapeHopSkipStep, ApItemId.HopSkipStepTape},
        {ApLocationId.TapeOnTheHour, ApItemId.OnTheHourTape},
        {ApLocationId.TapeLifeThroughLens, ApItemId.LifeThroughLensTape},
        {ApLocationId.TapePettingDeer, ApItemId.PettingDeerTape},
        {ApLocationId.TapeStoriesOfSnow, ApItemId.StoriesOfSnowTape},
        {ApLocationId.TapeTallShy, ApItemId.TallShyTape},
        {ApLocationId.TapeNightJam, ApItemId.NightJamTape},
        {ApLocationId.TapeWarmDaysNight, ApItemId.WarmDaysNightTape},
        {ApLocationId.TapeOneByOne, ApItemId.OneByOneTape},
        {ApLocationId.TapeHammockDays, ApItemId.HammockDaysTape},
        {ApLocationId.TapeSailorsTune, ApItemId.SailorsTuneTape},
        {ApLocationId.TapeSongOfTheSea, ApItemId.SongOfTheSeaTape},
    };

    public static readonly Dictionary<ApItemId, Quest.QuestRegion> ApItemIdToQuestRegion = new() {
        {ApItemId.StampHomelanda, Quest.QuestRegion.Home},
        {ApItemId.StampOaklaville, Quest.QuestRegion.Forest},
        {ApItemId.StampStanhamn, Quest.QuestRegion.Harbor},
        {ApItemId.StampLogcity, Quest.QuestRegion.City},
        {ApItemId.StampKiiruberg, Quest.QuestRegion.Mountain},
        {ApItemId.StampBasto, Quest.QuestRegion.Resort},
        {ApItemId.ProgressiveStamp, Quest.QuestRegion.Generic},
    };
    
    public static readonly Dictionary<ApItemId, string> ApItemIdToItem = new() {
        {ApItemId.Clogs, "Clogs"},
        {ApItemId.AwardMask, "AwardMask"},
        {ApItemId.Finger, "FoamFinger"},
        {ApItemId.Tripod, "Tripod"},
        {ApItemId.CowboyHat, "CowboyHat"},
        {ApItemId.WetSocks, "Pair of Socks"},
        {ApItemId.FjallbjornHat, "ScoutHat"},
        {ApItemId.GhostGlasses, "Sunglasses"},
        {ApItemId.SoakedSock, "Soaked Sock"},
        {ApItemId.MonsterMask, "MonsterMask"},
        {ApItemId.FramesFilters, "Camera Frames"},
        {ApItemId.FishingHat, "FishingHat"},
        {ApItemId.HonkAttachment, "Honk"},
        {ApItemId.Umbrella, "Umbrella"},
        {ApItemId.OldKey, "Pirate Key"},
        {ApItemId.HardHat, "Hardhat"},
        {ApItemId.DivingHelmet, "DiverHelmet"},
        {ApItemId.RubberBoots, "Rubber Boots"},
        {ApItemId.Sandwich, "SupremeSandwich"},
        {ApItemId.PirateHat, "PirateHat"},
        {ApItemId.PaperHat, "PaperHat"},
        {ApItemId.Flag, "PhotoFlag"},
        {ApItemId.HotbeanHat, "Hotbean Hat"},
        {ApItemId.ReporterHat, "ReporterHat"},
        {ApItemId.Sneakers, "Sneakers"},
        {ApItemId.CinnamonBun, "Cinnamonbun"},
        {ApItemId.Frisbee, "Frisbee"},
        {ApItemId.ClimbingBoots, "Snow Boots"},
        {ApItemId.PufferHat, "Puff Hat"},
        {ApItemId.Scarf, "Scarf"},
        {ApItemId.SkiGoggles, "SkiGoggles"},
        {ApItemId.SpaceHelmet, "SpaceHelmet"},
        {ApItemId.BastoTicket, "Bastu Ticket"},
        {ApItemId.Watergun, "Water Balloon Popper Attachment"},
        {ApItemId.SunHat, "Sunhat"},
        {ApItemId.Melonear, "Fruit Pear"},
        {ApItemId.Banakin, "Fruit Banana"},
        {ApItemId.Oranganas, "Fruit Orange"},
        {ApItemId.Beanut, "Fruit Bean"},
        {ApItemId.Pickaxe, "Pickaxe"},
        {ApItemId.SunCap, "Suncap"},
        {ApItemId.FlipFlops, "Flipflops"},
        {ApItemId.IceCream, "Ice Cream"},
        {ApItemId.RoyalCape, "Royal Cape"},
        {ApItemId.MinigameTicket, "MiniGame Ticket"},
        {ApItemId.Lei, "Lei"},
        {ApItemId.VacationShirt, "Vacation Shirt"},
        {ApItemId.RoyalCane, "Royal Cane"},
        {ApItemId.EmptyBottle, "Water Bottle Empty"},
        {ApItemId.VikingHelmet, "Viking Helmet"},
        {ApItemId.FootCast, "Foot Cast"},
        {ApItemId.Beret, "Beret"},
        {ApItemId.RoyalCrown, "Royal Crown"},
        // Cassettes
        {ApItemId.PhotoOfHomeTape, "Jamal Green - Photo of Home "},
        {ApItemId.SummerBreezeTape, "Jamal Green - Summer Breeze"},
        {ApItemId.SquirrelHotelTape, "Jamal Green - The Grand Squirrel Hotel"},
        {ApItemId.PineNeedlesTape, "Launchable Socks - Pine Needles"},
        {ApItemId.SquirrelPhotoTape, "Launchable Socks - Squirrel Photography"},
        {ApItemId.FishermansWhistleTape, "Fisherman's Whistle"},
        {ApItemId.SmilingHuntsmanTape, "JG+LS - The Smiling Huntsman"},
        {ApItemId.NautTape, "Jamal Green - Naut"},
        {ApItemId.PlaceInSunTape, "Launchable Socks - A Place In The Sun"},
        {ApItemId.FishermansTuneTape, "Launchable Socks - Fisherman's Tune"},
        {ApItemId.RatskullzThemeTape, "Anes Sabanovic - Ratskullz Theme"},
        {ApItemId.BigCityTape, "JG+LS - The Big City"},
        {ApItemId.HustleBustleTape, "Jamal Green - Hustle Bustle Shuffle"},
        {ApItemId.HopSkipStepTape, "Launchable Socks - Hop Skip Step"},
        {ApItemId.OnTheHourTape, "Launchable Socks - On The Hour"},
        {ApItemId.LifeThroughLensTape, "Jamal Green - Life Through a Lens"},
        {ApItemId.PettingDeerTape, "Jamal Green - The Petting of a Sacred Deer "},
        {ApItemId.StoriesOfSnowTape, "Launchable Socks - Stories Of Snow"},
        {ApItemId.TallShyTape, "Launchable Socks - Tall & Shy"},
        {ApItemId.NightJamTape, "JG+LS - Night Jam"},
        {ApItemId.WarmDaysNightTape, "Jamal Green - A Warm Days Night"},
        {ApItemId.OneByOneTape, "Jamal Green - One By One"},
        {ApItemId.HammockDaysTape, "Launchable Socks - Hammock Days"},
        {ApItemId.SailorsTuneTape, "Launchable Socks - Sailor's Tune"},
        {ApItemId.SongOfTheSeaTape, "Launchable Socks - Song Of The Sea"},
    };
    
    public static readonly Dictionary<string, string> RegionSceneName = new() {
        {"home", "Home"},
        {"forest", "Forest"},
        {"harbor", "Harbor"},
        {"city", "City"},
        {"mountainTop", "MountainTop"},
        {"mountain", "Mountain"},
        {"resort", "Resort"},
    };
    
    // Note that the transition uses the vanilla target scene not the exiting scene
    public static readonly Dictionary<string, Dictionary<int, string>> SceneTransitionToEntrance = new() {
        {"homeRoomPlayer", new() {{1, "Player room entrance"}}},
        {"homeRoomLiving", new() {{1, "Player room exit"}, {2, "Homelanda house entrance"}}},
        {"homeHouse", new() {{2, "Homelanda house exit"}}},
        {"forestBusStop", new() {{0, "Outside hotel down"}}},
        {"forestHotel", new() {{0, "Oaklaville bus stop exit"}, {20, "Hotel exit"},
            {1, "Ghost cup game right"}, {2, "Scout camp left"}}},
        {"forestHotelInside", new() {{20, "Hotel entrance"}, {33, "Hotel elevator exit"}}},
        {"forestHotelElevator", new() {{33, "Hotel elevator entrance"}}},
        {"forestHideIntersection", new() {{1, "Outside hotel left"},
            {2, "Hide and seek right"}, {20, "Mushroom house exit"}}},
        {"forestMushroomInside", new() {{20, "Mushroom house entrance"}}},
        {"forestHideAndSeek", new() {{2, "Ghost cup game left"}, {5, "Graveyard right"}}},
        {"forestGraveyard", new() {{5, "Hide and seek left"}, 
            {12, "Skeleton house exit"}, {41, "Skeleton house balcony exit"}}},
        {"forestGraveyardInside", new() {{12, "Skeleton house entrance"}, {41, "Skeleton house balcony entrance"}}},
        {"forestCamp", new() {{2, "Outside hotel right"}, 
            {10, "Oaklaville trail down"}, {5, "Playground left"}}},
        {"forestTrail0", new() {{10, "Scout camp up"}, {1, "Lookout exit"}}},
        {"forestTrail1", new() {{1, "Oaklaville trail up"}}},
        {"forestPlayground", new() {{5, "Scout camp right"}, {13, "Outside rave left"}}},
        {"forestRaveIntersection", new() {{13, "Playground right"}, {5, "Rave exit"}}},
        {"forestRave", new() {{5, "Rave entrance"}}},
        {"harborBusStop", new() {{10, "Photo guild hut exit"}, 
            {5, "Pirate Drawbridge right"}, {2, "Docks left exit"}}},
        {"harborPhotoGuildInside", new() {{10, "Photo guild hut entrance"}}},
        {"harborBridgeBeachCentrum", new() {{5, "Stanhamn bus stop left"}, {1, "Hippo beach right"}}},
        {"harborBeach", new() {{1, "Pirate Drawbridge left"}, 
            {9, "Underwater exit"}, {2, "Outside lighthouse right"}}},
        {"harborUnderwater", new() {{9, "Hippo beach manhole"}}},
        {"harborHonkhouse", new() {{2, "Hippo beach left"}, 
            {80, "Lighthouse exit"}, {1, "King fish beach exit"}}},
        {"harborHonkHouseInside", new() {{80, "Lighthouse entrance"}, {8, "Lighthouse roof exit"}}},
        {"harborHonkHouseTop", new() {{8, "Lighthouse roof entrance"}}},
        {"harborCliffs", new() {{1, "Outside lighthouse up"}}},
        {"harborDocks", new() {{2, "Stanhamn bus stop right"}, {1, "Fishing tower left"}}},
        {"harborFishingTower", new() {{1, "Docks right exit"}, {2, "Ghost drawbridge down"}}},
        {"harborBridgeFishingHydro", new() {{2, "Fishing tower up"}, {5, "Outside hydroplant right"}}},
        {"harborHydroplant", new() {{5, "Ghost drawbridge left"}, {8, "Hydroplant exit"}}},
        {"harborHydroplant_Inside", new() {{8, "Hydroplant entrance"}}},
        {"cityBusStop", new() {{1, "Logcity bus stop entrance"}}},
        {"cityHub", new() {{8, "Cross walk right"}, {4, "Outside cafe left"}, 
            {1, "Escalator up"}, {3, "Outside fashion show down"}}},
        {"cityParking", new() {{8, "Clock tower left"}, {1, "Overpass down"}}},
        {"cityOverpass", new() {{4, "Outside fashion show left"}, {1, "Cross walk up"},
            {3, "Skate park down"}, {15, "News house exit"}}},
        {"cityNewsHouseInside", new() {{15, "News house entrance"}}},
        {"citySkateboard", new() {{3, "Overpass up"}, {1, "Ratskullz alley exit"}, {500, "Outside cafe taxi"}}},
        {"cityAlley", new() {{1, "Skate park right"}}},
        {"cityBigTown", new() {{4, "Overpass right"}, {3, "Clock tower up"},
            {2, "Outside gallery show left"}, {20, "Fashion show exit"}}},
        {"cityFashionShow", new() {{20, "Fashion show entrance"}, {201, "Fashion show backstage exit"}}},
        {"cityFashionShowBackstage", new() {{201, "Fashion show backstage entrance"}}},
        {"cityCafe", new() {{4, "Clock tower right"}, {5, "Outside gallery show down"},
            {500, "Skate park taxi"}, {200, "Cafe exit"}}},
        {"cityCafeInside", new() {{200, "Cafe entrance"}}},
        {"cityGallery", new() {{5, "Outside cafe up"},
            {2, "Outside fashion show right"}, {6, "Gallery exit"}}},
        {"cityGalleryInside", new() {{6, "Gallery entrance"}}},
        {"mountainBusStop", new() {{1, "Birthday party down"}}},
        {"mountainTown", new() {{3, "Ski lift base left"}, {4, "Frozen pond right"},
            {2, "Snowman square down"}, {1, "Kiiruberg bus stop up"}, {23, "Balloon house exit"}}},
        {"mountainTownInside", new() {{23, "Balloon house entrance"}}},
        {"mountainLakeLonely", new() {{4, "Birthday party left"}, {8, "Old man's house exit"}}},
        {"mountainOldManInside", new() {{8, "Old man's house entrance"}}},
        {"mountainTown2", new() {{2, "Birthday party up"}, {8, "Outside wizard tower right"},
            {5, "Cliffs down"}, {80, "Meck's house exit"}, {100, "Military base exit"}}},
        {"mountainMilitary", new() {{100, "Military base entrance"}}},
        {"mountainMeckInside", new() {{80, "Meck's house entrance"}}},
        {"mountainWizard", new() {{8, "Snowman square left"}, {99, "Wizard tower exit"}}},
        {"mountainWizardInside", new() {{99, "Wizard tower entrance"}, {999, "Wizard portal exit"}}},
        {"CosmoGarden", new() {{999, "Wizard portal entrance"}}},
        {"mountainCliff", new() {{5, "Snowman square up"},
            {1, "Outside observatory down"}, {2, "Blizzard bridge left"}}},
        {"mountainWindyLobby", new() {{2, "Cliffs right"},
            {3, "Blizzard monster exit"}, {200, "Man cave exit"}}},
        {"mountainManCave", new() {{200, "Man cave entrance"}}},
        {"mountainWindyEnd", new() {{3, "Blizzard bridge right"}}},
        {"mountainObservatoryTop", new() {{1, "Cliffs up"},
            {2, "Ski mountain top left"}, {40, "Observatory exit"}}},
        {"mountainObservatory", new() {{40, "Observatory entrance"}}},
        {"mountainSkiCabin", new() {{3, "Birthday party right"}, {9, "Ski lodge exit"}}},
        {"mountainSkiCabinInside", new() {{9, "Ski lodge entrance"}}},
        {"mountainSkiTop", new() {{2, "Outside observatory right"}}},
        {"mountainTop", new() {{0, "Toem descend"}}},
        {"mountainTopToem", new() {{0, "Mountain top bus stop climb"}}},
        {"resortBusstop", new() {{1, "Lily pad pond down"}}},
        {"resortCenter", new() {{1, "Basto harbor up"}, {4, "Outside castle down"},
            {3, "Ghost hangout left"}, {2, "Campsite right"}}},
        {"resortNana", new() {{2, "Lily pad pond left"}, {10, "Tent exit"}}},
        {"resortHomeTent", new() {{10, "Tent entrance"}}},
        {"resortCastle", new() {{4, "Lily pad pond up"}, {2, "Castle exit"},
            {20, "Gym house exit"}, {5, "Bonfire lower right"}}},
        {"resortCastleInside", new() {{2, "Castle entrance"}}},
        {"resortDrinkInside", new() {{20, "Gym house entrance"}}},
        {"resortDino", new() {{5, "Outside castle left"}, {7, "Carnival exit"}, {12, "Jungle left"}}},
        {"resortCarnivalInside", new() {{7, "Carnival entrance"}}},
        {"resortGhost", new() {{3, "Lily pad pond right"}, {40, "Ghost hangout cave exit"}}},
        {"resortCaveTrail", new() {{40, "Ghost hangout cave entrance"},
            {10, "Secret cave room exit"}, {41, "Jungle cave entrance"}}},
        {"resortSecretCave", new() {{10, "Secret cave room entrance"}}},
        {"resortJungle", new() {{41, "Jungle cave exit"}, {12, "Bonfire upper right"}}},
    };

    public static readonly Dictionary<string, Tuple<string, int>> EntranceToSceneTransition = new() {
        {"Player room exit", Tuple.Create("homeRoomPlayer", 1)},
        {"Player room entrance", Tuple.Create("homeRoomLiving", 1)},
        {"Homelanda house exit", Tuple.Create("homeRoomLiving", 2)},
        {"Homelanda house entrance", Tuple.Create("homeHouse", 2)},
        {"Oaklaville bus stop exit", Tuple.Create("forestBusStop", 0)},
        {"Outside hotel down", Tuple.Create("forestHotel", 0)},
        {"Outside hotel left", Tuple.Create("forestHotel", 1)},
        {"Outside hotel right", Tuple.Create("forestHotel", 2)},
        {"Hotel entrance", Tuple.Create("forestHotel", 20)},
        {"Hotel exit", Tuple.Create("forestHotelInside", 20)},
        {"Hotel elevator entrance", Tuple.Create("forestHotelInside", 33)},
        {"Hotel elevator exit", Tuple.Create("forestHotelElevator", 33)},
        {"Ghost cup game right", Tuple.Create("forestHideIntersection", 1)},
        {"Ghost cup game left", Tuple.Create("forestHideIntersection", 2)},
        {"Mushroom house entrance", Tuple.Create("forestHideIntersection", 20)},
        {"Mushroom house exit", Tuple.Create("forestMushroomInside", 20)},
        {"Hide and seek right", Tuple.Create("forestHideAndSeek", 2)},
        {"Hide and seek left", Tuple.Create("forestHideAndSeek", 5)},
        {"Graveyard right", Tuple.Create("forestGraveyard", 5)},
        {"Skeleton house balcony entrance", Tuple.Create("forestGraveyard", 41)},
        {"Skeleton house entrance", Tuple.Create("forestGraveyard", 12)},
        {"Skeleton house balcony exit", Tuple.Create("forestGraveyardInside", 41)},
        {"Skeleton house exit", Tuple.Create("forestGraveyardInside", 12)},
        {"Scout camp left", Tuple.Create("forestCamp", 2)},
        {"Scout camp right", Tuple.Create("forestCamp", 5)},
        {"Scout camp up", Tuple.Create("forestCamp", 10)},
        {"Playground left", Tuple.Create("forestPlayground", 5)},
        {"Playground right", Tuple.Create("forestPlayground", 13)},
        {"Outside rave left", Tuple.Create("forestRaveIntersection", 13)},
        {"Rave entrance", Tuple.Create("forestRaveIntersection", 5)},
        {"Rave exit", Tuple.Create("forestRave", 5)},
        {"Oaklaville trail up", Tuple.Create("forestTrail0", 1)},
        {"Oaklaville trail down", Tuple.Create("forestTrail0", 10)},
        {"Lookout exit", Tuple.Create("forestTrail1", 1)},
        {"Stanhamn bus stop right", Tuple.Create("harborBusStop", 2)},
        {"Stanhamn bus stop left", Tuple.Create("harborBusStop", 5)},
        {"Photo guild hut entrance", Tuple.Create("harborBusStop", 10)},
        {"Photo guild hut exit", Tuple.Create("harborPhotoGuildInside", 10)},
        {"Pirate Drawbridge left", Tuple.Create("harborBridgeBeachCentrum", 1)},
        {"Pirate Drawbridge right", Tuple.Create("harborBridgeBeachCentrum", 5)},
        {"Hippo beach manhole", Tuple.Create("harborBeach", 9)},
        {"Hippo beach left", Tuple.Create("harborBeach", 2)},
        {"Hippo beach right", Tuple.Create("harborBeach", 1)},
        {"Underwater exit", Tuple.Create("harborUnderwater", 9)},
        {"Outside lighthouse right", Tuple.Create("harborHonkhouse", 2)},
        {"Outside lighthouse up", Tuple.Create("harborHonkhouse", 1)},
        {"Lighthouse entrance", Tuple.Create("harborHonkhouse", 80)},
        {"Lighthouse roof entrance", Tuple.Create("harborHonkHouseInside", 8)},
        {"Lighthouse exit", Tuple.Create("harborHonkHouseInside", 80)},
        {"Lighthouse roof exit", Tuple.Create("harborHonkHouseTop", 8)},
        {"King fish beach exit", Tuple.Create("harborCliffs", 1)},
        {"Docks left exit", Tuple.Create("harborDocks", 2)},
        {"Docks right exit", Tuple.Create("harborDocks", 1)},
        {"Fishing tower up", Tuple.Create("harborFishingTower", 2)},
        {"Fishing tower left", Tuple.Create("harborFishingTower", 1)},
        {"Ghost drawbridge down", Tuple.Create("harborBridgeFishingHydro", 2)},
        {"Ghost drawbridge left", Tuple.Create("harborBridgeFishingHydro", 5)},
        {"Outside hydroplant right", Tuple.Create("harborHydroplant", 5)},
        {"Hydroplant entrance", Tuple.Create("harborHydroplant", 8)},
        {"Hydroplant exit", Tuple.Create("harborHydroplant_Inside", 8)},
        {"Escalator up", Tuple.Create("cityBusStop", 1)},
        {"Clock tower left", Tuple.Create("cityHub", 8)},
        {"Clock tower right", Tuple.Create("cityHub", 4)},
        {"Logcity bus stop entrance", Tuple.Create("cityHub", 1)},
        {"Clock tower up", Tuple.Create("cityHub", 3)},
        {"Cross walk right", Tuple.Create("cityParking", 8)},
        {"Cross walk up", Tuple.Create("cityParking", 1)},
        {"Overpass right", Tuple.Create("cityOverpass", 4)},
        {"Overpass down", Tuple.Create("cityOverpass", 1)},
        {"Overpass up", Tuple.Create("cityOverpass", 3)},
        {"News house entrance", Tuple.Create("cityOverpass", 15)},
        {"News house exit", Tuple.Create("cityNewsHouseInside", 15)},
        {"Skate park down", Tuple.Create("citySkateboard", 3)},
        {"Skate park right", Tuple.Create("citySkateboard", 1)},
        {"Skate park taxi", Tuple.Create("citySkateboard", 500)},
        {"Ratskullz alley exit", Tuple.Create("cityAlley", 1)},
        {"Outside fashion show left", Tuple.Create("cityBigTown", 4)},
        {"Outside fashion show down", Tuple.Create("cityBigTown", 3)},
        {"Outside fashion show right", Tuple.Create("cityBigTown", 2)},
        {"Fashion show entrance", Tuple.Create("cityBigTown", 20)},
        {"Fashion show exit", Tuple.Create("cityFashionShow", 20)},
        {"Fashion show backstage entrance", Tuple.Create("cityFashionShow", 201)},
        {"Fashion show backstage exit", Tuple.Create("cityFashionShowBackstage", 201)},
        {"Outside cafe left", Tuple.Create("cityCafe", 4)},
        {"Outside cafe up", Tuple.Create("cityCafe", 5)},
        {"Outside cafe taxi", Tuple.Create("cityCafe", 500)},
        {"Cafe entrance", Tuple.Create("cityCafe", 200)},
        {"Cafe exit", Tuple.Create("cityCafeInside", 200)},
        {"Outside gallery show down", Tuple.Create("cityGallery", 5)},
        {"Outside gallery show left", Tuple.Create("cityGallery", 2)},
        {"Gallery entrance", Tuple.Create("cityGallery", 6)},
        {"Gallery exit", Tuple.Create("cityGalleryInside", 6)},
        {"Kiiruberg bus stop up", Tuple.Create("mountainBusStop", 1)},
        {"Birthday party right", Tuple.Create("mountainTown", 3)},
        {"Birthday party left", Tuple.Create("mountainTown", 4)},
        {"Birthday party up", Tuple.Create("mountainTown", 2)},
        {"Birthday party down", Tuple.Create("mountainTown", 1)},
        {"Balloon house entrance", Tuple.Create("mountainTown", 23)},
        {"Balloon house exit", Tuple.Create("mountainTownInside", 23)},
        {"Frozen pond right", Tuple.Create("mountainLakeLonely", 4)},
        {"Old man's house entrance", Tuple.Create("mountainLakeLonely", 8)},
        {"Old man's house exit", Tuple.Create("mountainOldManInside", 8)},
        {"Snowman square down", Tuple.Create("mountainTown2", 2)},
        {"Snowman square left", Tuple.Create("mountainTown2", 8)},
        {"Snowman square up", Tuple.Create("mountainTown2", 5)},
        {"Meck's house entrance", Tuple.Create("mountainTown2", 80)},
        {"Military base entrance", Tuple.Create("mountainTown2", 100)},
        {"Military base exit", Tuple.Create("mountainMilitary", 100)},
        {"Meck's house exit", Tuple.Create("mountainMeckInside", 80)},
        {"Outside wizard tower right", Tuple.Create("mountainWizard", 8)},
        {"Wizard tower entrance", Tuple.Create("mountainWizard", 99)},
        {"Wizard tower exit", Tuple.Create("mountainWizardInside", 99)},
        {"Wizard portal entrance", Tuple.Create("mountainWizardInside", 999)},
        {"Wizard portal exit", Tuple.Create("CosmoGarden", 999)},
        {"Cliffs down", Tuple.Create("mountainCliff", 5)},
        {"Cliffs up", Tuple.Create("mountainCliff", 1)},
        {"Cliffs right", Tuple.Create("mountainCliff", 2)},
        {"Blizzard bridge left", Tuple.Create("mountainWindyLobby", 2)},
        {"Blizzard bridge right", Tuple.Create("mountainWindyLobby", 3)},
        {"Man cave entrance", Tuple.Create("mountainWindyLobby", 200)},
        {"Man cave exit", Tuple.Create("mountainManCave", 200)},
        {"Blizzard monster exit", Tuple.Create("mountainWindyEnd", 3)},
        {"Outside observatory down", Tuple.Create("mountainObservatoryTop", 1)},
        {"Outside observatory right", Tuple.Create("mountainObservatoryTop", 2)},
        {"Observatory entrance", Tuple.Create("mountainObservatoryTop", 40)},
        {"Observatory exit", Tuple.Create("mountainObservatory", 40)},
        {"Ski lift base left", Tuple.Create("mountainSkiCabin", 3)},
        {"Ski lodge entrance", Tuple.Create("mountainSkiCabin", 9)},
        {"Ski lodge exit", Tuple.Create("mountainSkiCabinInside", 9)},
        {"Ski mountain top left", Tuple.Create("mountainSkiTop", 2)},
        {"Mountain top bus stop climb", Tuple.Create("mountainTop", 0)},
        {"Toem descend", Tuple.Create("mountainTopToem", 0)},
        {"Basto harbor up", Tuple.Create("resortBusstop", 1)},
        {"Lily pad pond down", Tuple.Create("resortCenter", 1)},
        {"Lily pad pond up", Tuple.Create("resortCenter", 4)},
        {"Lily pad pond right", Tuple.Create("resortCenter", 3)},
        {"Lily pad pond left", Tuple.Create("resortCenter", 2)},
        {"Campsite right", Tuple.Create("resortNana", 2)},
        {"Tent entrance", Tuple.Create("resortNana", 10)},
        {"Tent exit", Tuple.Create("resortHomeTent", 10)},
        {"Outside castle down", Tuple.Create("resortCastle", 4)},
        {"Castle entrance", Tuple.Create("resortCastle", 2)},
        {"Gym house entrance", Tuple.Create("resortCastle", 20)},
        {"Outside castle left", Tuple.Create("resortCastle", 5)},
        {"Castle exit", Tuple.Create("resortCastleInside", 2)},
        {"Gym house exit", Tuple.Create("resortDrinkInside", 20)},
        {"Bonfire lower right", Tuple.Create("resortDino", 5)},
        {"Carnival entrance", Tuple.Create("resortDino", 7)},
        {"Bonfire upper right", Tuple.Create("resortDino", 12)},
        {"Carnival exit", Tuple.Create("resortCarnivalInside", 7)},
        {"Ghost hangout left", Tuple.Create("resortGhost", 3)},
        {"Ghost hangout cave entrance", Tuple.Create("resortGhost", 40)},
        {"Ghost hangout cave exit", Tuple.Create("resortCaveTrail", 40)},
        {"Secret cave room entrance", Tuple.Create("resortCaveTrail", 10)},
        {"Jungle cave exit", Tuple.Create("resortCaveTrail", 41)},
        {"Secret cave room exit", Tuple.Create("resortSecretCave", 10)},
        {"Jungle cave entrance", Tuple.Create("resortJungle", 41)},
        {"Jungle left", Tuple.Create("resortJungle", 12)},
    };
}
